const refs = [
  { name: 'NIST Cybersecurity Framework 2.0', org: 'NIST', url: 'https://www.nist.gov/cyberframework', tag: '프레임워크', desc: '보안 위험을 식별하고 우선순위를 정하는 공통 언어' },
  { name: 'KISA ISMS-P', org: 'KISA', url: 'https://isms.kisa.or.kr/', tag: '국내 기준', desc: '국내 정보보호·개인정보보호 관리체계 공식 자료' },
  { name: 'Microsoft Defender for Endpoint', org: 'Microsoft Learn', url: 'https://learn.microsoft.com/en-us/defender-endpoint/', tag: 'EDR', desc: '엔드포인트 온보딩, 탐지, 대응과 운영 가이드' },
  { name: 'OWASP Developer Guide', org: 'OWASP', url: 'https://owasp.org/www-project-developer-guide/', tag: '웹 보안', desc: '웹 애플리케이션 보안 원칙과 테스트 가이드' },
  { name: 'MITRE ATT&CK', org: 'MITRE', url: 'https://attack.mitre.org/', tag: '위협 분석', desc: '공격 전술·기술을 운영 탐지와 연결하는 지식베이스' },
  { name: 'IETF RFC Index', org: 'IETF', url: 'https://www.rfc-editor.org/', tag: '네트워크', desc: 'TCP/IP와 인터넷 프로토콜의 원문 표준' },
  { name: 'RFC 1122 Host Requirements', org: 'IETF', url: 'https://www.rfc-editor.org/rfc/rfc1122', tag: 'TCP/IP', desc: '인터넷 프로토콜 계층과 호스트 요구사항의 공식 표준' },
  { name: 'TCP/IP Learning Center', org: 'Cloudflare', url: 'https://www.cloudflare.com/learning/ddos/glossary/tcp-ip/', tag: '입문 설명', desc: '비전공자도 이해하기 쉬운 TCP/IP 개념 설명' },
  { name: 'Known Exploited Vulnerabilities', org: 'CISA', url: 'https://www.cisa.gov/known-exploited-vulnerabilities-catalog', tag: '취약점 사례', desc: '실제 공격에 악용된 취약점과 조치 우선순위' },
  { name: 'NIST SP 800-61 Rev. 3', org: 'NIST', url: 'https://csrc.nist.gov/pubs/sp/800/61/r3/final', tag: '사고 대응', desc: '사이버보안 사고 대응 권고사항과 고려사항' },
  { name: 'FortiGate Administration Guide', org: 'Fortinet', url: 'https://docs.fortinet.com/document/fortigate/7.6.1/administration-guide/383477/summary-of-steps', tag: '방화벽·VPN', desc: '방화벽 정책, 관리망, IPsec VPN 구축·운영 흐름' },
  { name: 'PAN-OS Security Policy', org: 'Palo Alto Networks', url: 'https://docs.paloaltonetworks.com/pan-os/11-1/pan-os-admin/policy/security-policy', tag: 'NGFW', desc: 'Zone·주소·애플리케이션·사용자·서비스 기반 정책 운영' },
  { name: 'F5 BIG-IP Documentation', org: 'F5', url: 'https://techdocs.f5.com/', tag: 'ADC·WAF', desc: '애플리케이션 전달, 로드밸런싱과 웹방화벽 운영 자료' },
  { name: 'Microsoft Defender for Endpoint', org: 'Microsoft Learn', url: 'https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint', tag: 'Endpoint', desc: '단말 텔레메트리, 탐지·대응과 보안 운영 개요' },
  { name: 'Microsoft Defender for Office 365', org: 'Microsoft Learn', url: 'https://learn.microsoft.com/en-us/defender-office-365/', tag: '메일 보안', desc: '피싱·악성 메일·첨부파일·URL 보호와 조사' },
]

const sectorMeta = [
  { id: 'network', icon: '◎', color: 'cyan', title: '기초 네트워크', en: 'NETWORK FOUNDATION', desc: 'TCP/IP와 트래픽 흐름을 읽는 힘', outcome: '패킷 흐름과 장애 지점을 설명할 수 있다.' },
  { id: 'endpoint', icon: '◈', color: 'violet', title: '단말 보안', en: 'ENDPOINT SECURITY', desc: 'EDR·백신·DLP·NAC 운영', outcome: '단말 정책과 탐지 이벤트를 운영할 수 있다.' },
  { id: 'network-security', icon: '▣', color: 'amber', title: '네트워크 보안', en: 'NETWORK SECURITY', desc: 'Firewall·IPS·VPN·WAF 운영', outcome: '접근제어 정책과 보안 장비 장애를 분석할 수 있다.' },
  { id: 'policy', icon: '≡', color: 'green', title: '정책 운영', en: 'POLICY OPERATIONS', desc: '배포·예외·변경·롤백 프로세스', outcome: '변경 근거와 영향도를 기록하고 통제할 수 있다.' },
  { id: 'incident', icon: '△', color: 'red', title: '로그·장애 대응', en: 'INCIDENT RESPONSE', desc: '로그 분석과 원인 규명', outcome: '장애를 재현·분리·조치하고 재발을 방지할 수 있다.' },
  { id: 'customer', icon: '⊙', color: 'blue', title: 'B2B 고객 운영', en: 'CUSTOMER OPERATIONS', desc: 'SLA·기술 협의·정기 보고', outcome: '기술 내용을 고객 언어와 보고서로 전환할 수 있다.' },
  { id: 'automation', icon: '⌁', color: 'pink', title: '운영 자동화', en: 'AUTOMATION', desc: '반복 업무를 안전하게 줄이기', outcome: '검증 가능한 스크립트와 운영 자동화를 설계할 수 있다.' },
  { id: 'career', icon: '↗', color: 'white', title: '취업 대비', en: 'CAREER READINESS', desc: '경력기술서·면접·자격증', outcome: '운영 경험을 증거와 성과 중심으로 설명할 수 있다.' },
]

const topicSeeds = {
  network: [
    ['TCP/IP 4계층', 'TCP/IP model', '기초', '계층별 역할과 캡슐화를 이해하고 장애 범위를 좁힌다.', '클라이언트 요청이 애플리케이션에서 NIC까지 내려가는 과정을 4계층으로 설명한다.', 'OSI 7계층과 TCP/IP 4계층을 대응시키고, 각 계층의 대표 로그를 적어본다.'],
    ['DNS와 HTTP 흐름', 'DNS / HTTP', '기초', '이름 해석부터 TLS, HTTP 응답까지의 정상 흐름을 기준선으로 만든다.', 'DNS는 성공하지만 HTTPS만 실패하는 상황에서 확인 순서를 설계한다.', 'nslookup/dig, curl, 브라우저 개발자 도구에서 확인할 지점을 정리한다.'],
    ['라우팅과 방화벽 기초', 'Routing / Firewall', '기초', '경로, 포트, 상태 추적을 분리해 네트워크 장애를 분석한다.', '특정 대역에서만 서버 443 포트가 타임아웃되는 장애를 분석한다.', '출발지·목적지·포트·경로·정책 순으로 확인하는 5단계 템플릿을 작성한다.'],
    ['패킷·로그 읽기', 'Packet & Log Reading', '실무', '패킷과 장비 로그에서 사실과 추정을 구분한다.', 'SYN 재전송이 반복되는 캡처를 보고 네트워크·서버·정책 후보를 분리한다.', '타임스탬프, 5-tuple, 상태코드, 상관관계 ID를 추출한다.'],
  ],
  endpoint: [
    ['EDR 운영 모델', 'EDR Operations', '기초', '수집·탐지·분석·격리·복구의 운영 생명주기를 이해한다.', '의심스러운 PowerShell 실행 이벤트가 들어온 뒤 초기 대응을 수행한다.', '탐지 심각도, 호스트 중요도, 사용자 영향으로 우선순위를 정한다.'],
    ['백신 정책과 예외', 'AV Policy', '기초', '실시간 보호, 검사 주기, 예외의 위험을 정책으로 관리한다.', '업무 프로그램이 오탐되는 상황에서 무조건 예외를 주지 않고 검증한다.', '예외 대상·기간·승인자·대체 통제를 기록한다.'],
    ['DLP 데이터 흐름', 'DLP', '실무', '데이터 분류와 채널 통제를 연결해 유출 위험을 줄인다.', 'USB로 대량 파일이 복사된 경보의 사실관계를 확인한다.', '데이터 유형, 사용자, 채널, 행위, 업무 필요성을 기준으로 판단한다.'],
    ['NAC 접근제어', 'NAC', '실무', '단말 식별·상태평가·격리·복귀 흐름을 운영한다.', '보안 에이전트가 중지된 단말이 격리망으로 이동한 상황을 조치한다.', '인증 실패와 정책 불일치를 구분하고 복귀 조건을 기록한다.'],
  ],
  'network-security': [
    ['Firewall 정책 설계', 'Firewall Rule Design', '기초', '최소권한과 명확한 객체·서비스·방향으로 정책을 설계한다.', '신규 B2B 고객의 HTTPS 연동 요청을 정책으로 변환한다.', '정책 목적, 출발지, 목적지, 서비스, 기간, 로그 여부를 정의한다.'],
    ['IPS 탐지와 예외', 'IPS Detection', '실무', '탐지 시그니처와 실제 공격 가능성을 분리해 예외를 통제한다.', '정상 API 호출이 공격 시그니처로 탐지된 이벤트를 검증한다.', '시그니처·원본 페이로드·반복성·대체 방어를 확인한다.'],
    ['VPN 인증·터널', 'VPN', '실무', '인증, 암호화, 터널, 라우팅을 분리해 접속 장애를 분석한다.', '인증은 성공하지만 내부 시스템에 접속되지 않는 장애를 분석한다.', '사용자 인증→터널→주소 할당→라우팅→목적지 정책 순으로 확인한다.'],
    ['WAF 요청 분석', 'WAF', '실무', '웹 요청·응답과 WAF 정책의 관계를 분석한다.', '특정 파라미터가 차단되어 403이 발생하는 이슈를 재현·완화한다.', 'URI, 메서드, 파라미터, 룰 ID, 원본 서버 응답을 비교한다.'],
  ],
  policy: [
    ['정책 배포 절차', 'Policy Deployment', '기초', '요청-검토-승인-테스트-배포-검증의 흐름을 표준화한다.', '긴급 차단 정책을 배포하면서 서비스 영향과 롤백을 함께 준비한다.', '변경 티켓, 사전 검증, 승인, 배포 시각, 사후 검증을 남긴다.'],
    ['예외 승인 관리', 'Exception Management', '실무', '예외는 영구 허용이 아니라 만료와 보완 통제를 가진 위험 수용이다.', '업무상 필요한 예외 요청의 위험도를 평가한다.', '사유·범위·만료일·승인자·대체 통제·재검토일을 기록한다.'],
    ['변경·롤백', 'Change & Rollback', '실무', '변경 전후 상태와 실패 시 복구 경로를 관리한다.', '정책 변경 후 일부 고객의 연결이 끊겨 즉시 롤백한다.', '변경 단위, 백업, 성공 기준, 관찰 시간, 롤백 트리거를 정의한다.'],
    ['SOP와 증적', 'SOP & Evidence', '실무', '반복 가능한 운영절차와 감사 가능한 증적을 만든다.', '감사 요청에 정책 이력과 승인 기록을 빠르게 제출한다.', '문서 버전, 소유자, 승인일, 점검 주기, 관련 티켓을 연결한다.'],
  ],
  incident: [
    ['로그 수집과 기준선', 'Logging Baseline', '기초', '정상 상태와 시간 동기화를 기준으로 이상을 찾는다.', '장비별 시간이 달라 사건 순서가 뒤섞인 로그를 정렬한다.', 'NTP, 소스, 필드, 보존기간, 수집 누락을 점검한다.'],
    ['장애 트리아지', 'Incident Triage', '실무', '영향도와 긴급도로 사건을 분류하고 대응자를 정한다.', '다수 고객의 접속 장애가 발생한 상황에서 우선순위를 정한다.', '영향 범위·확산성·보안성·복구 난이도로 우선순위를 점수화한다.'],
    ['원인 분석 RCA', 'Root Cause Analysis', '실무', '증상·직접 원인·기여 요인·근본 원인을 분리한다.', '정책 배포 이후 탐지량이 급증한 사건의 RCA를 작성한다.', '타임라인, 증거, 가설, 검증 결과, 재발 방지책을 기록한다.'],
    ['사고 후 개선', 'Post-Incident Review', '실무', '복구가 끝난 뒤 탐지·절차·문서·자동화를 개선한다.', '반복 장애의 액션 아이템을 담당자와 기한까지 확정한다.', '무엇이 잘못됐는지보다 어떤 통제를 개선할지 측정 가능하게 쓴다.'],
  ],
  customer: [
    ['B2B 이슈 접수', 'B2B Intake', '기초', '고객 표현을 기술 사실과 업무 영향으로 번역한다.', '고객이 “보안 솔루션이 전부 멈췄다”고 문의한 상황을 정리한다.', '고객·시각·영향·재현·최근 변경·증거를 한 장으로 정리한다.'],
    ['SLA와 우선순위', 'SLA & Priority', '실무', '기술 심각도와 고객 서비스 중요도를 함께 판단한다.', '긴급 장애와 단일 사용자 문의가 동시에 들어온 상황을 배분한다.', '응답 목표, 복구 목표, 중간 공지 주기, 에스컬레이션 조건을 확인한다.'],
    ['기술 협의 진행', 'Technical Workshop', '실무', '가정·제약·결정사항을 명시해 협의를 실행계획으로 바꾼다.', '고객의 방화벽 변경 요청을 보안·운영 조건과 함께 검토한다.', '아젠다, 결정권자, 액션, 기한, 미결 이슈를 회의록에 남긴다.'],
    ['정기 운영 보고', 'Service Reporting', '실무', '운영량보다 위험·추세·조치 중심으로 보고한다.', '월간 보고서에서 탐지 증가를 장애가 아닌 개선 지표로 설명한다.', 'KPI, 주요 사건, 정책 변경, 미해결 위험, 다음 달 계획을 제시한다.'],
  ],
  automation: [
    ['운영 자동화 원칙', 'Automation Guardrails', '기초', '자동화 범위·승인·검증·중단 장치를 먼저 설계한다.', '대량 정책 변경 스크립트의 오작동 위험을 줄인다.', 'dry-run, 입력 검증, 권한 최소화, 감사 로그, 롤백을 포함한다.'],
    ['로그 검색 쿼리', 'Log Querying', '실무', '필터·집계·상관관계로 반복 분석 시간을 줄인다.', '특정 호스트의 로그인 실패와 EDR 탐지를 시간순으로 묶는다.', '시간창, 키 필드, 중복 제거, 결과 보존, 오탐 검증을 적용한다.'],
    ['정책 검증 스크립트', 'Policy Validation', '실무', '변경 전후 정책의 누락·중복·과도한 허용을 자동 점검한다.', 'any-any 규칙과 만료된 예외를 사전 탐지한다.', '정책 ID, 소유자, 만료일, 영향 서비스, 승인 티켓을 검사한다.'],
    ['운영 자동화 포트폴리오', 'Automation Portfolio', '실무', '효과와 위험을 비교해 자동화 우선순위를 정한다.', '수작업 보고서 생성을 자동화할지 판단한다.', '빈도·절감시간·오류위험·복구가능성·데이터 민감도를 평가한다.'],
  ],
  career: [
    ['경력기술서 구조', 'Experience Story', '취업', '상황-행동-결과로 운영 경험을 증거화한다.', 'EDR 운영 경험을 제품 나열이 아닌 성과로 바꿔 쓴다.', '대상·문제·내 역할·조치·수치·재발 방지까지 한 사례로 정리한다.'],
    ['기술면접 대비', 'Technical Interview', '취업', '정답보다 판단 순서와 운영 trade-off를 설명한다.', 'VPN 접속 장애 질문에 확인 순서와 고객 커뮤니케이션을 함께 답한다.', '가설→확인→조치→검증→보고의 구조로 답변을 연습한다.'],
    ['자격증 로드맵', 'Certification Path', '취업', '정보보안기사·ISMS-P·CISSP의 목적과 시기를 구분한다.', '현재 경력과 학습 시간에 맞는 우선순위를 정한다.', '응시요건, 출제범위, 실무 연결성, 준비 기간을 비교한다.'],
    ['12주 포트폴리오', '12-week Portfolio', '취업', '학습 기록을 운영 플레이북과 면접 포트폴리오로 묶는다.', '12주 후 실제로 보여줄 산출물을 계획한다.', '네트워크 진단서, 정책변경서, RCA, 월간보고서, 자동화 예제를 완성한다.'],
  ],
}

const topics = Object.entries(topicSeeds).flatMap(([sector, items]) => items.map((item, index) => ({
  id: `${sector}-${index + 1}`, sector, title: item[0], en: item[1], level: item[2], summary: item[3], scenario: item[4], practice: item[5],
  terms: item[1].split(' / '),
  checks: ['핵심 개념을 내 말로 설명하기', '운영 절차를 순서대로 적기', '실무 시나리오의 확인 항목 만들기', '면접 답변 또는 운영 산출물 남기기'],
  questions: [`${item[0]}을 운영할 때 가장 먼저 확인할 것은 무엇인가?`, '정상 기준선과 예외 상황을 어떻게 구분할 것인가?', '변경 또는 조치 이후 성공 여부를 어떻게 검증할 것인가?'],
  refs: sector === 'network' ? [refs[5], refs[0]] : sector === 'endpoint' ? [refs[2], refs[4]] : sector === 'career' ? [refs[0], refs[1]] : [refs[0], refs[1]],
})))

const state = {
  page: 'dashboard', search: '', filter: '전체', selectedTopic: null,
  completed: JSON.parse(localStorage.getItem('secops-completed') || '{}'),
  notes: JSON.parse(localStorage.getItem('secops-notes') || '{}'),
  examFilter: '전체', examIndex: 0, examAnswers: JSON.parse(localStorage.getItem('secops-exam') || '{}'),
}

function routeSnapshot() {
  return { page: state.page, search: state.search, filter: state.filter, selectedTopic: state.selectedTopic, examFilter: state.examFilter, examIndex: state.examIndex }
}

function routeUrl() {
  const url = new URL(window.location.href)
  ;['page', 'topic', 'filter', 'q'].forEach((key) => url.searchParams.delete(key))
  if (state.page !== 'dashboard') url.searchParams.set('page', state.page)
  if (state.page === 'study' && state.selectedTopic) url.searchParams.set('topic', state.selectedTopic)
  if (state.page === 'learn' && state.filter !== '전체') url.searchParams.set('filter', state.filter)
  if (state.page === 'exam') {
    if (state.examFilter !== '전체') url.searchParams.set('filter', state.examFilter)
    if (state.examIndex) url.searchParams.set('q', String(state.examIndex))
  }
  return `${url.pathname}${url.search}${url.hash}`
}

function syncRoute(replace = false) {
  window.history[replace ? 'replaceState' : 'pushState'](routeSnapshot(), '', routeUrl())
}

function restoreRoute(route = {}) {
  const validPages = ['dashboard', 'learn', 'study', 'exam', 'roadmap', 'matrix', 'architecture', 'refs']
  state.page = validPages.includes(route.page) ? route.page : 'dashboard'
  state.selectedTopic = topics.some((t) => t.id === route.selectedTopic) ? route.selectedTopic : null
  state.search = typeof route.search === 'string' ? route.search : ''
  state.filter = route.filter || '전체'
  state.examFilter = route.examFilter || '전체'
  state.examIndex = Number.isFinite(Number(route.examIndex)) ? Number(route.examIndex) : 0
}

const save = () => { localStorage.setItem('secops-completed', JSON.stringify(state.completed)); localStorage.setItem('secops-notes', JSON.stringify(state.notes)) }
const esc = (value) => String(value).replace(/[&<>"']/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))
const sector = (id) => sectorMeta.find((item) => item.id === id)
const doneCount = () => Object.values(state.completed).filter(Boolean).length
const pct = (n, total = topics.length) => Math.round((n / total) * 100)

function icon(name) {
  const icons = { dashboard: '⌂', learn: '◫', study: '▤', exam: '✓', roadmap: '↗', matrix: '⊞', architecture: '⌘', refs: '◌' }
  return icons[name] || '•'
}

function appShell(content) {
  return `<div class="app-shell"><aside class="sidebar"><div class="brand"><div class="brand-mark">S</div><div><strong>SECOPS</strong><span>FIELD GUIDE / 01</span></div></div><div class="side-label">NAVIGATION</div><nav>${[['dashboard','대시보드','Overview'],['learn','학습센터','Learning center'],['study','공부하기','Study center'],['exam','기사 문제','Engineer questions'],['roadmap','12주 로드맵','Study plan'],['matrix','역량 매트릭스','Job mapping'],['architecture','대기업 망구조','Enterprise architecture'],['refs','레퍼런스','Official sources']].map(([id,kr,en]) => `<button class="nav-item ${state.page === id ? 'active' : ''}" data-page="${id}"><span class="nav-icon">${icon(id)}</span><span><b>${kr}</b><small>${en}</small></span></button>`).join('')}</nav><div class="sidebar-bottom"><div class="mini-progress"><div class="side-label">YOUR PROGRESS</div><div class="progress-number">${pct(doneCount())}<small>%</small></div><div class="progress-track"><i style="width:${pct(doneCount())}%"></i></div><p>${doneCount()} / ${topics.length} topics completed</p></div><div class="status-pill"><i></i> LOCAL MODE <span>●</span></div></div></aside><main class="main"><header class="topbar"><div class="breadcrumb">SECOPS FIELD GUIDE <span>/</span> ${state.page.toUpperCase()}</div><button class="reset-btn" id="reset-progress">진도 초기화</button></header>${content}</main></div>`
}

function dashboard() {
  const next = topics.find((t) => !state.completed[t.id]) || topics[0]
  const weak = sectorMeta.map((s) => ({ ...s, count: topics.filter((t) => t.sector === s.id).filter((t) => state.completed[t.id]).length })).sort((a,b) => a.count / 4 - b.count / 4)[0]
  return appShell(`<section class="page fade-in"><div class="hero"><div><div class="eyebrow"><i></i> OPERATIONS READINESS PROGRAM / 2026</div><h1>보안 운영,<br><em>다시 현장으로.</em></h1><p>5년의 공백을 실무 역량으로 연결하는<br>정보보안 솔루션 운영 학습 플레이북입니다.</p><button class="primary-btn" data-topic="${next.id}">다음 학습 시작 <span>→</span></button></div><div class="hero-orbit"><div class="orbit-ring ring-1"></div><div class="orbit-ring ring-2"></div><div class="orbit-ring ring-3"></div><div class="orbit-core"><span>OPS</span><b>${String(pct(doneCount())).padStart(2,'0')}</b><small>% READY</small></div><div class="orbit-dot dot-a"></div><div class="orbit-dot dot-b"></div><div class="orbit-dot dot-c"></div></div></div><div class="section-heading"><div><span class="eyebrow">COMMAND CENTER</span><h2>현재 학습 상태</h2></div><span class="live-tag"><i></i> LOCAL STORAGE ACTIVE</span></div><div class="stats-grid"><div class="stat-card accent"><span class="stat-label">TOTAL PROGRESS</span><strong>${pct(doneCount())}<small>%</small></strong><div class="progress-track"><i style="width:${pct(doneCount())}%"></i></div><p>${doneCount()}개 학습 주제 완료</p></div><div class="stat-card"><span class="stat-label">CURRENT PHASE</span><strong class="phase">${doneCount() < 8 ? '01' : doneCount() < 20 ? '02' : '03'} <small>/ 03</small></strong><p>${doneCount() < 8 ? '기초 기반 세우기' : doneCount() < 20 ? '운영 시나리오 훈련' : '취업 실전 준비'}</p></div><div class="stat-card"><span class="stat-label">WEAK SIGNAL</span><strong class="signal">${weak.title}</strong><p>${4 - weak.count}개 주제 남음 · 우선 학습 권장</p></div><div class="stat-card"><span class="stat-label">NEXT MILESTONE</span><strong class="milestone">12주</strong><p>운영 포트폴리오 완성 목표</p></div></div><div class="dashboard-grid"><div class="panel sector-panel"><div class="panel-head"><div><span class="eyebrow">SECTOR SCAN</span><h3>역량별 진행 현황</h3></div><button class="text-btn" data-page="learn">전체 보기 →</button></div><div class="sector-list">${sectorMeta.map((s) => { const done = topics.filter((t) => t.sector === s.id && state.completed[t.id]).length; return `<button class="sector-row" data-sector="${s.id}"><span class="sector-icon ${s.color}">${s.icon}</span><span class="sector-info"><b>${s.title}</b><small>${s.en}</small></span><span class="sector-bar"><i style="width:${pct(done,4)}%"></i></span><strong>${String(pct(done,4)).padStart(2,'0')}<small>%</small></strong><span class="row-arrow">↗</span></button>` }).join('')}</div></div><div class="panel focus-panel"><span class="eyebrow">RECOMMENDED NEXT</span><h3>${esc(next.title)}</h3><span class="topic-sector ${sector(next.sector).color}">${sector(next.sector).title} / ${next.level}</span><p>${esc(next.summary)}</p><div class="focus-bottom"><span>예상 35분</span><button class="circle-btn" data-topic="${next.id}">→</button></div></div></div></section>`)
}

function learnPage() {
  const filtered = topics.filter((t) => { const q = state.search.toLowerCase(); return (!q || `${t.title} ${t.en} ${t.summary}`.toLowerCase().includes(q)) && (state.filter === '전체' || t.sector === state.filter || t.level === state.filter) })
  return appShell(`<section class="page fade-in"><div class="page-title"><div><span class="eyebrow">KNOWLEDGE BASE / 08 SECTORS</span><h1>학습 섹터</h1><p>기초 개념에서 운영 문서와 면접 답변까지, 한 주제를 끝까지 연결합니다.</p></div><div class="title-count"><strong>${filtered.length}</strong><span>VISIBLE TOPICS</span></div></div><div class="toolbar"><div class="search-box"><span>⌕</span><input id="search" value="${esc(state.search)}" placeholder="주제, 용어, 운영 키워드 검색" /></div><div class="filter-wrap"><button class="filter-btn ${state.filter === '전체' ? 'selected' : ''}" data-filter="전체">전체</button>${sectorMeta.map((s) => `<button class="filter-btn ${state.filter === s.id ? 'selected' : ''}" data-filter="${s.id}">${s.title}</button>`).join('')}<button class="filter-btn ${state.filter === '실무' ? 'selected' : ''}" data-filter="실무">실무</button><button class="filter-btn ${state.filter === '취업' ? 'selected' : ''}" data-filter="취업">취업</button></div></div><div class="topic-grid">${filtered.map(topicCard).join('')}</div></section>`)
}

function topicCard(t) { const s = sector(t.sector); const complete = state.completed[t.id]; return `<article class="topic-card ${complete ? 'complete' : ''}" data-topic="${t.id}"><div class="card-top"><span class="sector-icon ${s.color}">${s.icon}</span><span class="topic-level">${t.level}</span><button class="check-btn ${complete ? 'checked' : ''}" data-complete="${t.id}">${complete ? '✓' : '○'}</button></div><span class="card-kicker">${s.en}</span><h3>${esc(t.title)}</h3><p>${esc(t.summary)}</p><div class="card-foot"><span>${t.terms.join(' · ')}</span><b>열기 ↗</b></div></article>` }

function roadmap() { const weeks = [['01–02','기초 기반','네트워크·로그·보안 운영의 공통 언어를 회복합니다.',['TCP/IP 4계층','DNS와 HTTP 흐름','로그 수집과 기준선','정책 배포 절차']],['03–05','솔루션 운영','단말과 네트워크 보안 장비의 운영 흐름을 익힙니다.',['EDR 운영 모델','백신 정책과 예외','Firewall 정책 설계','VPN 인증·터널','WAF 요청 분석']],['06–08','장애·고객 대응','트리아지, RCA, SLA와 기술 협의를 훈련합니다.',['장애 트리아지','원인 분석 RCA','B2B 이슈 접수','SLA와 우선순위','정기 운영 보고']],['09–10','자동화·문서화','정책 검증과 반복 업무 자동화 산출물을 만듭니다.',['운영 자동화 원칙','로그 검색 쿼리','정책 검증 스크립트','SOP와 증적']],['11–12','취업 실전','경험을 경력기술서와 기술면접 답변으로 전환합니다.',['경력기술서 구조','기술면접 대비','자격증 로드맵','12주 포트폴리오']]]; return appShell(`<section class="page fade-in"><div class="page-title"><div><span class="eyebrow">FIELD TRAINING / 12 WEEKS</span><h1>12주 로드맵</h1><p>매주 하나의 운영 산출물을 남기며 공백기를 실무 언어로 바꿉니다.</p></div></div><div class="roadmap">${weeks.map((w,i) => `<div class="roadmap-row"><div class="week-marker"><span>PHASE ${String(i+1).padStart(2,'0')}</span><strong>${w[0]}</strong></div><div class="roadmap-content"><div><span class="eyebrow">${w[1]}</span><h2>${w[2]}</h2></div><div class="roadmap-topics">${w[3].map((name) => {const t=topics.find(x=>x.title===name); return t ? `<button data-topic="${t.id}" class="roadmap-topic ${state.completed[t.id]?'done':''}"><i>${state.completed[t.id]?'✓':'○'}</i>${name}<span>→</span></button>` : ''}).join('')}</div></div></div>`).join('')}</div></section>`) }

const jobProfiles = [
  {
    id: 'job-a', badge: '공고 A / 보안솔루션 운영·유지보수', title: '단말·네트워크 보안솔루션 운영형', summary: 'NAC·방화벽·VPN·nDLP와 EPP·안티 랜섬웨어·PMS·eDLP·DRM·망연계솔루션을 운영하고, 웹쉘 탐지·개인정보 접근 이력관리와 금융보안 규제 대응까지 수행하는 포지션입니다.',
    tags: ['NAC', 'FW/VPN', 'nDLP·eDLP', 'EPP·DRM', '금융보안·전자금융거래법', 'AWS'],
    skills: [
      ['단말 보안 제품 운영', 'endpoint', 'EDR 운영 모델', '탐지 이벤트·정책·예외·격리 대응 기록'],
      ['네트워크 접근제어', 'network-security', 'VPN 인증·터널', '인증 성공 후 내부망 미접속 장애 분석서'],
      ['DLP·개인정보 통제', 'endpoint', 'DLP 데이터 흐름', '데이터·사용자·채널별 차단/예외 판단표'],
      ['변경·규제 준수', 'policy', 'SOP와 증적', '전자금융·금융보안 점검 대응 증적 목록'],
      ['웹쉘·침해 징후 대응', 'incident', '장애 트리아지', '탐지부터 격리·복구까지의 타임라인'],
    ],
    preferred: '정보보안기사·CISSP·CISA, 보안솔루션 구축·운영, AWS 클라우드 보안 경험'
  },
  {
    id: 'job-b', badge: '공고 B / 신세계아이앤씨 정보보안', title: '하이브리드 보안 인프라·거버넌스형', summary: '내·외부 위협 식별과 개선, IT 보안시스템 기획·구축·운영, 애플리케이션 취약점 관리, 24×365 관제·침해사고 대응, 개인정보·ISMS·감사·보안인식까지 연결하는 포지션입니다.',
    tags: ['하이브리드 인프라', 'PoC/BMT', '취약점 관리', '24×365 관제', 'ISMS·감사', '보안인식'],
    skills: [
      ['보안 인프라 아키텍처', 'network-security', 'Firewall 정책 설계', '온프레미스·클라우드 경계와 최소권한 설계도'],
      ['솔루션 도입·고도화', 'automation', '운영 자동화 포트폴리오', 'PoC/BMT 평가표와 도입 후 KPI'],
      ['취약점·위협 개선', 'incident', '원인 분석 RCA', '취약점 영향도·조치기한·재검증 보고서'],
      ['관제·침해사고 대응', 'incident', '사고 후 개선', '24×365 에스컬레이션·RCA·재발방지 계획'],
      ['ISMS·감사·개인정보', 'policy', 'SOP와 증적', '관리체계 증적·내외부 점검 대응 체크리스트'],
      ['조직 보안 커뮤니케이션', 'customer', '기술 협의 진행', '보안인식 교육안과 의사결정 회의록'],
    ],
    preferred: '보안인프라 설계·구축·운영, 대규모 조직 경험, ISA·CISSP·CPPG·정보보안기사 등'
  },
  {
    id: 'job-c', badge: '공고 C / SK 채용 대비', title: '보안 아키텍처·솔루션 구축형', summary: '최신 IT기술을 활용한 보안 아키텍처 설계·구축부터 보안솔루션 기획·정책 적용·성능 최적화·이슈 대응·로그 분석까지 수행하는 포지션입니다. 접근제어, 백신, 웹서버, 메일, 원격접속, 인터넷, 데이터, Endpoint 보안을 폭넓게 다룹니다.',
    tags: ['보안 아키텍처', '솔루션 구축·운영', '접근제어', '웹·메일 보안', '데이터보안', '글로벌 협업'],
    skills: [
      ['아키텍처 설계·연동', 'network', 'TCP/IP 4계층', '사용자·인터넷·보안장비·서버 구간 설계도'],
      ['접근제어·원격접속', 'network-security', 'VPN 인증·터널', '인증·터널·라우팅·정책 장애 분석서'],
      ['Endpoint·백신 운영', 'endpoint', 'EDR 운영 모델', '단말 온보딩·탐지·격리·복구 운영표'],
      ['웹서버·메일·인터넷 보안', 'network-security', 'WAF 요청 분석', 'HTTP/WAF/메일 보안 흐름과 차단 근거'],
      ['로그 분석·성능 최적화', 'incident', '로그 수집과 기준선', '성능 지표·로그 상관분석·개선 보고서'],
      ['기획·제안·구축 검증', 'automation', '운영 자동화 포트폴리오', '요구사항·PoC·BMT·전환·운영 KPI'],
    ],
    preferred: '정보보안(산업)기사·PIA·ISMS-P 심사원·ISO 27001, 서버·네트워크, 솔루션 구축·제안, 글로벌 커뮤니케이션'
  }
]

function jobProfileCard(profile) {
  return `<article class="job-profile"><div class="job-profile-head"><span class="eyebrow">${profile.badge}</span><span class="job-profile-mark">JD</span></div><h2>${profile.title}</h2><p class="job-summary">${profile.summary}</p><div class="job-tags">${profile.tags.map((tag) => `<span>${tag}</span>`).join('')}</div><div class="job-skill-list"><div class="job-skill-head"><span>필요 역량</span><span>학습 연결</span></div>${profile.skills.map(([label, sec, topicTitle, evidence]) => { const t = topics.find((item) => item.title === topicTitle); const s = sector(sec); return `<div class="job-skill-row"><div><strong>${label}</strong><small>${evidence}</small></div><button class="job-topic-link" data-topic="${t.id}"><i class="sector-icon ${s.color}">${s.icon}</i>${topicTitle} ↗</button></div>` }).join('')}</div><div class="job-preferred"><b>우대·확장 역량</b><p>${profile.preferred}</p></div></article>`
}

function architectureBlueprint() {
  const layers = [
    ['사용자·단말', 'Endpoint / EPP / EDR / 백신 / DLP', '인증·단말 상태·데이터 반출'],
    ['접속 경계', 'NAC / VPN / ZTNA / 접근제어', '신원·기기·위치·정책 평가'],
    ['인터넷·네트워크', 'Firewall / IPS / DNS / Proxy', '경로·세션·위협 탐지·차단'],
    ['웹·메일·데이터', 'WAF / Mail Security / DRM / DB·개인정보', '요청·첨부파일·민감정보 통제'],
    ['관제·관리', 'SIEM / SOAR / 로그 / 티켓 / 리포트', '상관분석·대응·감사·개선'],
  ]
  return `<section class="architecture-panel"><div class="section-heading"><div><span class="eyebrow">REFERENCE ARCHITECTURE / CONTROL PLANE</span><h2>보안솔루션 연동 구조</h2></div><span class="live-tag"><i></i> DESIGN → BUILD → OPERATE</span></div><p class="architecture-lead">SK 공고의 “아키텍처 설계·구축·운영”을 하나의 흐름으로 연습할 수 있도록 사용자 요청부터 정책 판단, 보안장비 처리, 로그·관제·개선까지 연결한 공통 구조입니다.</p><div class="architecture-diagram">${layers.map(([name, tools, control], i) => `<div class="architecture-node"><span>${String(i + 1).padStart(2, '0')}</span><strong>${name}</strong><b>${tools}</b><small>${control}</small></div>${i < layers.length - 1 ? '<div class="architecture-arrow">↓</div>' : ''}`).join('')}</div><div class="solution-catalog"><div class="solution-catalog-head"><span>솔루션군</span><span>핵심 학습 질문</span><span>운영 산출물</span></div>${[['접근제어·NAC·VPN','누가, 어떤 단말로, 어느 구간에 접근하는가?','접근정책·예외승인·접속장애 RCA'],['Firewall·IPS·인터넷 보안','어떤 흐름을 어떤 기준으로 허용·차단하는가?','정책설계서·hit count·차단 근거'],['Endpoint·백신·DLP·DRM','단말 행위와 데이터 반출을 어떻게 판단하는가?','탐지분석·격리기록·예외 만료표'],['웹서버·WAF·메일 보안','요청·첨부·URL이 정상인지 어떻게 검증하는가?','WAF 룰 분석·피싱 조사·재현 결과'],['로그·SIEM·관제','여러 장비의 사건을 어떻게 하나의 타임라인으로 묶는가?','상관분석·에스컬레이션·월간 보고']].map((row) => `<div class="solution-catalog-row"><strong>${row[0]}</strong><span>${row[1]}</span><span>${row[2]}</span></div>`).join('')}</div><div class="architecture-note"><b>설계 시 반드시 남길 것</b><span>신뢰경계·데이터 흐름·관리망·장애 우회·로그 위치·성능 병목·롤백 경로·운영 담당자</span></div></section>`
}

const enterpriseControls = [
  ['NAC', '사내 접속 스위치·무선·VPN 진입점', '단말 인증, posture 점검, 격리 VLAN, 복귀 승인', '비인가 단말·취약 단말의 내부망 진입', '802.1X/RADIUS와 단말 상태 정책으로 정상 단말만 업무 VLAN에 배치', '인증 실패·에이전트 중지 로그 확인 → 격리망 이동 → 조치 후 재평가'],
  ['VPN / ZTNA / MFA', '원격 사용자와 지사 연결 경계', '사용자·단말·애플리케이션별 원격 접근과 세션 관리', '탈취 계정·무단 원격접속·과도한 내부 접근', 'MFA, 기기 신뢰도, 분할 터널/애플리케이션 단위 권한, 세션 만료', '계정 잠금·토큰 폐기 → 세션/인증 로그 보존 → 영향 계정과 접근정책 재검토'],
  ['Firewall / NGFW', '인터넷 경계·DMZ·내부 세그먼트 사이', 'Zone·주소·서비스·사용자·애플리케이션 정책, NAT, 관리망 분리', '불필요한 포트 노출·횡적 이동·C2 통신', '최소권한 정책, 기본 거부, 세션 검사, 애플리케이션 식별과 로그', 'deny/hit count와 양방향 경로 확인 → 긴급 차단은 승인·만료·롤백까지 기록'],
  ['IPS / IDS', '방화벽 뒤 또는 핵심 트래픽 미러링 구간', '시그니처·행위·취약점 기반 탐지, 오탐 예외와 룰 튜닝', '스캔·익스플로잇·악성 통신·프로토콜 이상', '패킷 패턴·세션·취약 자산 맥락을 결합해 차단 또는 경보', '원본 패킷·룰 ID·대상 자산 확인 → 임시 완화·패치·예외 승인 검증'],
  ['Proxy / DNS Security', '사용자 인터넷 출구와 이름 해석 경로', 'URL·도메인·카테고리·악성 IP·DNS 질의 모니터링', '피싱·악성 다운로드·DNS 기반 C2·잘못된 외부 접속', '정책 기반 URL/DNS 차단, 안전한 재귀 DNS, 캐시·도메인 평판 사용', '사용자·단말·도메인·시간을 묶어 조사 → DNS 차단·브라우저 격리·IOC 전파'],
  ['WAF / ADC', '공개 웹 DMZ의 Load Balancer 앞단', 'HTTP 메서드·URI·헤더·파라미터·세션·TLS 종료와 라우팅', 'SQLi·XSS·경로 조작·웹쉘 업로드·비정상 봇', '정규화·룰 검사·rate limit·가상패치·원본 서버 은닉', 'WAF 룰 ID와 원본 응답 비교 → 정상 오탐은 좁은 예외 → 침해 시 세션·파일·서버 격리'],
  ['Mail Security', '인터넷 메일 게이트웨이와 클라우드 메일 앞단', '발신자 인증, URL·첨부파일 검사, 격리함과 사용자 신고', '피싱·BEC·악성 첨부·악성 링크·스푸핑', 'SPF/DKIM/DMARC, 샌드박스, URL 재작성·격리·발신자 평판', '동일 발신·URL·첨부 해시 검색 → 전사 회수 → 계정·메일 규칙·피해 단말 조사'],
  ['EPP / AV / EDR', '노트북·VDI·서버 등 업무 단말 내부', '에이전트 상태·프로세스 트리·파일·레지스트리·네트워크 행위', '랜섬웨어·악성코드·스크립트·자격증명 탈취·지속성', '행위 탐지, 파일 격리, 프로세스 종료, 네트워크 격리와 IOC 검색', '호스트 격리 전 업무 영향 판단 → 증거 수집 → 계정·IOC 확산 검색 → 복구·재발 방지'],
  ['PMS / Patch Management', '단말·서버 관리망과 자산 관리 콘솔', '자산 식별, OS·애플리케이션 버전, 패치 배포와 실패율', '미패치 취약점 악용·지원 종료 제품', '위험도·자산 중요도 기반 패치 링, 테스트 그룹, 실패 재시도', 'CVE 영향 자산 조회 → 보완 통제·긴급 패치 → 재스캔과 예외 만료 관리'],
  ['DLP / eDLP', '단말·메일·웹 업로드·파일공유·출력 경로', '데이터 분류, 사용자·채널·행위·업무 사유와 예외', '개인정보·소스코드·기밀자료의 외부 유출', '콘텐츠 검사·지문·패턴·암호화·차단/승인/감사 모드', '원본 파일·사용자·채널·수신처 확인 → 증거 보존 → 계정·파일 공유 회수'],
  ['DRM / 개인정보 접근감사', '문서 저장소·업무 앱·DB·개인정보 처리 구간', '문서 권한·열람·복사·출력·DB 조회 이력과 관리자 행위', '권한 남용·내부자 유출·개인정보 과다 조회', '최소권한, 문서 암호화, 워터마크, 접근 사유와 이상 조회 탐지', '접근 타임라인·권한 변경·다운로드 대조 → 권한 회수·보존·법무/개인정보 절차 연계'],
  ['SIEM / SOAR / SOC', '각 보안장비와 서버 로그의 중앙 관제 영역', '수집·정규화·상관분석·티켓·플레이북·지표', '분산된 공격의 은닉·탐지 지연·대응 누락', 'NAC·VPN·FW·WAF·EDR·메일 이벤트를 사용자/자산/시간으로 연결', '심각도 분류 → 플레이북 실행 → 담당자 에스컬레이션 → 타임라인·RCA·KPI 기록'],
]

function enterpriseTopology() {
  return `<div class="topology-block"><div class="section-heading"><div><span class="eyebrow">REFERENCE NETWORK TOPOLOGY / ZONE VIEW</span><h2>대기업 보안 망구조 아키텍처</h2></div><span class="live-tag"><i></i> TRAFFIC + TELEMETRY</span></div><p class="topology-lead">아래 그림은 외부망과 인터넷에서 들어온 요청이 경계 보안장비를 지나 DMZ·내부 업무망·데이터망으로 이동하는 구조입니다. 실선은 업무 트래픽, 점선은 각 장비에서 SOC로 올라가는 로그·이벤트 흐름입니다.</p><div class="topology-canvas"><svg viewBox="0 0 1440 760" role="img" aria-label="외부망, 방화벽, DMZ, 내부망, 데이터망, SOC가 연결된 대기업 보안 네트워크 구조">
    <defs><marker id="arrow-cyan" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#58d6ec"/></marker><marker id="arrow-amber" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#ffc965"/></marker></defs>
    <rect class="zone zone-external" x="20" y="35" width="190" height="650" rx="14"/><text class="zone-title" x="42" y="70">외부망 / 원격</text><text class="zone-sub" x="42" y="93">INTERNET / REMOTE</text>
    <rect class="zone zone-edge" x="235" y="35" width="220" height="650" rx="14"/><text class="zone-title" x="257" y="70">경계 보안망</text><text class="zone-sub" x="257" y="93">EDGE / ACCESS</text>
    <rect class="zone zone-dmz" x="480" y="35" width="260" height="650" rx="14"/><text class="zone-title" x="502" y="70">DMZ</text><text class="zone-sub" x="502" y="93">PUBLIC SERVICES</text>
    <rect class="zone zone-internal" x="765" y="35" width="250" height="650" rx="14"/><text class="zone-title" x="787" y="70">내부 업무망</text><text class="zone-sub" x="787" y="93">CORPORATE / APP</text>
    <rect class="zone zone-data" x="1040" y="35" width="180" height="650" rx="14"/><text class="zone-title" x="1062" y="70">데이터망</text><text class="zone-sub" x="1062" y="93">DATA / PRIVACY</text>
    <rect class="zone zone-soc" x="1245" y="35" width="175" height="650" rx="14"/><text class="zone-title" x="1267" y="70">관리·관제망</text><text class="zone-sub" x="1267" y="93">SOC / MGMT</text>

    <path class="traffic" d="M 175 190 L 245 190"/><path class="traffic" d="M 445 190 L 490 190"/><path class="traffic" d="M 730 190 L 775 190"/><path class="traffic" d="M 1005 190 L 1050 190"/>
    <path class="traffic" d="M 175 480 L 245 480"/><path class="traffic" d="M 445 480 L 490 480"/><path class="traffic" d="M 730 480 L 775 480"/>
    <path class="telemetry" d="M 335 280 C 560 300, 850 300, 1260 280"/><path class="telemetry" d="M 610 285 C 820 350, 1000 350, 1260 330"/><path class="telemetry" d="M 885 520 C 1020 555, 1120 500, 1260 420"/><path class="telemetry" d="M 1115 530 C 1160 570, 1210 530, 1260 470"/>

    <g class="topo-node external-node"><rect x="45" y="145" width="140" height="82" rx="8"/><text x="115" y="174">인터넷</text><text x="115" y="197">공격자·고객·파트너</text></g><g class="topo-node external-node"><rect x="45" y="435" width="140" height="82" rx="8"/><text x="115" y="464">재택·지사</text><text x="115" y="487">원격 사용자</text></g>
    <g class="topo-node edge-node"><rect x="255" y="145" width="180" height="82" rx="8"/><text x="345" y="173">DDoS / Edge Router</text><text x="345" y="197">인터넷 회선·기본 필터</text></g><g class="topo-node edge-node"><rect x="255" y="435" width="180" height="82" rx="8"/><text x="345" y="463">VPN / ZTNA / MFA</text><text x="345" y="487">인증·단말상태·접속정책</text></g><g class="topo-node edge-node"><rect x="270" y="265" width="150" height="90" rx="8"/><text x="345" y="297">방화벽 HA</text><text x="345" y="320">NGFW · IPS</text><text x="345" y="340">NAT·Zone·차단</text></g>
    <g class="topo-node dmz-node"><rect x="505" y="145" width="210" height="82" rx="8"/><text x="610" y="174">WAF / ADC</text><text x="610" y="198">TLS·HTTP·L7 보호·로드밸런싱</text></g><g class="topo-node dmz-node"><rect x="505" y="435" width="210" height="82" rx="8"/><text x="610" y="464">Mail / Proxy / DNS</text><text x="610" y="488">피싱·URL·악성 DNS·메일 격리</text></g><g class="topo-node dmz-node"><rect x="535" y="265" width="150" height="90" rx="8"/><text x="610" y="297">웹·API 서버</text><text x="610" y="320">공개 서비스 DMZ</text><text x="610" y="340">웹쉘·무결성 점검</text></g>
    <g class="topo-node internal-node"><rect x="790" y="145" width="200" height="82" rx="8"/><text x="890" y="174">Core / Segmentation FW</text><text x="890" y="198">내부 Zone·동서 트래픽 통제</text></g><g class="topo-node internal-node"><rect x="790" y="435" width="200" height="82" rx="8"/><text x="890" y="464">업무 앱·서버</text><text x="890" y="488">AD·API·파일·그룹웨어</text></g><g class="topo-node internal-node"><rect x="815" y="265" width="150" height="90" rx="8"/><text x="890" y="297">NAC</text><text x="890" y="320">스위치·무선·단말 인증</text><text x="890" y="340">격리 VLAN·복귀</text></g>
    <g class="topo-node data-node"><rect x="1060" y="145" width="140" height="82" rx="8"/><text x="1130" y="174">DB / 개인정보</text><text x="1130" y="198">접근감사·DLP</text></g><g class="topo-node data-node"><rect x="1060" y="435" width="140" height="82" rx="8"/><text x="1130" y="464">DRM / 문서</text><text x="1130" y="488">암호화·반출통제</text></g>
    <g class="topo-node soc-node"><rect x="1260" y="145" width="145" height="82" rx="8"/><text x="1332" y="174">SIEM / SOAR</text><text x="1332" y="198">상관분석·플레이북</text></g><g class="topo-node soc-node"><rect x="1260" y="435" width="145" height="82" rx="8"/><text x="1332" y="464">SOC / 관리망</text><text x="1332" y="488">티켓·RCA·보고</text></g>
    <text class="line-label" x="215" y="178">실선: 업무 트래픽</text><text class="telemetry-label" x="780" y="298">점선: 로그·이벤트·상태</text><text class="line-label" x="755" y="178">허용·차단 정책</text>
  </svg></div><div class="topology-legend"><span><i class="legend-line"></i> 업무 트래픽</span><span><i class="legend-dash"></i> 로그·텔레메트리</span><span><i class="legend-zone"></i> 보안 신뢰영역</span><b>※ 실제 구축에서는 이중화·클라우드·지사·DR센터를 추가합니다.</b></div></div>`
}

function enterpriseArchitecture() {
  const zones = [
    ['01', '사용자·단말 영역', '사내 PC·노트북·VDI·서버', 'NAC · EPP/EDR · AV · PMS · DLP · DRM'],
    ['02', '접속·경계 영역', '지사·재택·인터넷 진입점', 'MFA · VPN/ZTNA · Firewall/NGFW · IPS · Proxy/DNS'],
    ['03', 'DMZ·서비스 영역', '외부 공개 웹·메일·DNS 서비스', 'DDoS · WAF/ADC · Mail Security · Web/API'],
    ['04', '업무·데이터 영역', '내부 앱·DB·개인정보·문서 저장소', 'Segmentation · PAM · DB 감사 · DRM/DLP'],
    ['05', '관제·관리 영역', 'SOC·관리망·로그·티켓·백업', 'SIEM · SOAR · 취약점 관리 · 보고서'],
  ]
  return `<section class="enterprise-section"><div class="page-title enterprise-title"><div><span class="eyebrow">ENTERPRISE REFERENCE / LARGE NETWORK</span><h1>대기업 통합 보안망 구조</h1><p>실제 설계에서는 조직·서비스·클라우드·지사에 따라 달라지지만, 아래 구조를 기준으로 “어느 구간에 어떤 솔루션을 두고 어떤 증거를 남기는가”를 설명할 수 있어야 합니다.</p></div><div class="enterprise-legend"><span>공격 흐름</span><b>→</b><span>로그·관제 흐름</span><b class="telemetry">⇢</b></div></div>${enterpriseTopology()}<div class="enterprise-flow"><div class="flow-track attack-track"><span>외부 공격·사용자 요청</span>${zones.slice(0,4).map((z) => `<i>→</i><b>${z[1]}</b>`).join('')}<span>차단·허용·복구</span></div><div class="flow-track telemetry-track"><span>장비·단말 텔레메트리</span>${zones.map((z) => `<i>⇢</i><b>${z[1]}</b>`).join('')}<span>SOC 판단·대응</span></div></div><div class="enterprise-zones">${zones.map(([number, name, assets, controls]) => `<article class="enterprise-zone"><div class="zone-number">${number}</div><div><h2>${name}</h2><p>${assets}</p><strong>${controls}</strong></div></article>`).join('')}</div><div class="enterprise-runbook"><div class="section-heading"><div><span class="eyebrow">SOLUTION POSITION / OPERATION RUNBOOK</span><h2>솔루션별 배치·차단·대응</h2></div><span class="live-tag"><i></i> 12 CONTROL POINTS</span></div><div class="control-grid">${enterpriseControls.map(([name, place, operate, block, prevent, respond]) => `<article class="control-card"><div class="control-card-head"><h3>${name}</h3><span>CONTROL</span></div><dl><div><dt>네트워크 위치</dt><dd>${place}</dd></div><div><dt>평상시 운영</dt><dd>${operate}</dd></div><div><dt>막는 공격·위험</dt><dd>${block}</dd></div><div><dt>막는 방식</dt><dd>${prevent}</dd></div><div class="response"><dt>사고 대응</dt><dd>${respond}</dd></div></dl></article>`).join('')}</div></div><div class="enterprise-scenarios"><div class="section-heading"><div><span class="eyebrow">ATTACK PATH / DEFENSIVE RESPONSE</span><h2>공격 시나리오로 연결하기</h2></div></div>${[['피싱 메일 → 계정 탈취','Mail Security가 URL/첨부를 격리하고, 사용자가 클릭하면 Proxy/DNS와 EDR이 후속 행위를 탐지합니다. SIEM은 메일·로그인·단말 이벤트를 묶고, 대응자는 세션 폐기·계정 잠금·단말 격리·전사 메일 회수를 수행합니다.'],['공개 웹 공격 → 웹쉘 시도','WAF가 요청·업로드·비정상 패턴을 차단하고, IPS·EDR·웹 무결성 로그가 서버 행위를 감시합니다. 운영자는 원본 요청과 파일 해시를 보존한 뒤 WAF 룰·서버 격리·취약점 패치·재발행 검증을 진행합니다.'],['감염 단말 → 내부 확산','EPP/EDR이 프로세스 연쇄를 탐지하고 NAC가 단말을 격리 VLAN으로 이동시킵니다. Firewall·IPS는 동서 트래픽을 제한하며, SIEM/SOAR는 동일 IOC를 전사 검색합니다. 복구 전 패치·자격증명 교체·정상 통신 재검증을 수행합니다.'],['내부자 개인정보 과다조회 → 유출','DB 접근감사·DRM·DLP가 사용자·문서·조회량·반출 채널을 기록합니다. 이상 패턴을 탐지하면 권한과 세션을 제한하고 원본 증거·접근 이력·파일을 보존한 뒤 개인정보 사고 절차로 에스컬레이션합니다.']].map(([title, body], i) => `<article class="scenario-row"><b>SCENARIO 0${i + 1}</b><div><h3>${title}</h3><p>${body}</p></div></article>`).join('')}</div><div class="enterprise-note"><b>면접 답변 공식</b><span>“솔루션 이름”만 말하지 말고 <strong>배치 위치 → 관찰 데이터 → 차단 통제 → 운영 로그 → 사고 대응 → 복구 검증</strong> 순서로 설명하세요.</span></div></section>`
}

function architecturePage() { return appShell(`<section class="page fade-in">${enterpriseArchitecture()}</section>`) }

function matrix() {
  const rows = [['EDR·백신·DLP·NAC','endpoint','탐지·정책·예외·격리 운영'],['정책 배포·예외·변경관리','policy','승인·테스트·롤백·증적'],['Firewall·IPS·VPN·WAF','network-security','접근제어·탐지·터널·웹 요청'],['장애 분석·트러블슈팅','incident','로그·트리아지·RCA·재발방지'],['B2B 운영 지원·기술 협의','customer','SLA·회의록·에스컬레이션'],['정기 보고·문서화','customer','KPI·위험·조치·다음 계획'],['운영 자동화','automation','쿼리·검증·스크립트·가드레일']]
  return appShell(`<section class="page fade-in"><div class="page-title"><div><span class="eyebrow">JOB DESCRIPTION / MAPPING</span><h1>역량 매트릭스</h1><p>세 채용공고의 요구사항을 공통 역량과 공고별 학습 경로로 분해했습니다.</p></div></div><div class="job-profile-grid">${jobProfiles.map(jobProfileCard).join('')}</div>${architectureBlueprint()}<div class="section-heading job-matrix-heading"><div><span class="eyebrow">COMMON REQUIREMENTS</span><h2>공통 채용요건 매핑</h2></div><span class="live-tag"><i></i> TOPIC LINKED</span></div><div class="panel matrix-panel"><div class="matrix-header"><span>채용 요구사항</span><span>학습 섹터</span><span>준비할 증거</span><span>상태</span></div>${rows.map(([req,sec,evidence])=>{const s=sector(sec);const related=topics.filter(t=>t.sector===sec);const done=related.filter(t=>state.completed[t.id]).length; return `<div class="matrix-row"><strong>${req}</strong><span class="matrix-sector"><i class="sector-icon ${s.color}">${s.icon}</i>${s.title}</span><span>${evidence}</span><span class="matrix-status ${done===related.length?'ready':''}">${done===related.length?'READY':`${done}/${related.length}`}</span></div>`}).join('')}</div><div class="callout"><span>◎</span><div><b>면접에서 보여줄 운영 증거</b><p>정책 변경서, 장애 RCA, 월간 운영 보고서, 로그 분석 쿼리, 예외 승인 기록, PoC/BMT 평가표, ISMS·감사 증적을 포트폴리오 형태로 축적하세요.</p></div></div></section>`)
}

function examPage() {
  const list = state.examFilter === '전체' ? examQuestions : examQuestions.filter((q) => q.sector === state.examFilter); const q = list[state.examIndex % list.length]; const result = state.examAnswers[q.id]; const s = sector(q.sector); const solved = Object.values(state.examAnswers).filter((a) => a.solved).length; const correct = Object.values(state.examAnswers).filter((a) => a.correct).length;
  return appShell(`<section class="page fade-in exam-page"><div class="page-title"><div><span class="eyebrow">INFORMATION SECURITY ENGINEER / ORIGINAL QUESTIONS</span><h1>기사 문제</h1><p>실제 기출문제 복제가 아닌 오리지널 문제입니다. 이론을 읽은 뒤 문제로 이해 여부를 확인하세요.</p></div><div class="title-count"><strong>${correct}/${solved}</strong><span>ACCURACY / SOLVED</span></div></div><div class="exam-toolbar"><div class="exam-filters"><button class="filter-btn ${state.examFilter === '전체' ? 'selected' : ''}" data-exam-filter="전체">전체</button>${sectorMeta.map((item) => `<button class="filter-btn ${state.examFilter === item.id ? 'selected' : ''}" data-exam-filter="${item.id}">${item.title}</button>`).join('')}</div><a class="exam-ref" href="https://www.q-net.or.kr/crf005.do?id=crf00503s02&jmCd=7967&jmInfoDivCcd=B0" target="_blank" rel="noreferrer">Q-Net 종목 정보 ↗</a></div><div class="exam-layout"><aside class="exam-meta"><span class="eyebrow">QUESTION ${String((state.examIndex % list.length) + 1).padStart(2,'0')} / ${String(list.length).padStart(2,'0')}</span><div class="exam-sector"><i class="sector-icon ${s.color}">${s.icon}</i><div><b>${s.title}</b><small>${q.category}</small></div></div><div class="exam-score"><span>이번 세션 정답률</span><strong>${solved ? Math.round((correct / solved) * 100) : 0}<small>%</small></strong><div class="progress-track"><i style="width:${solved ? (correct / solved) * 100 : 0}%"></i></div></div><p class="exam-tip">문제를 풀기 전에 공부하기에서 해당 섹터의 이론과 사례를 먼저 읽어보세요.</p></aside><main class="question-card"><div class="question-label">Q${String((state.examIndex % list.length) + 1).padStart(2,'0')} / ${q.category}</div><h2>${q.q}</h2><div class="choices">${q.choices.map((choice, i) => { const picked = result?.picked === i; const right = result?.solved && i === q.answer; const wrong = result?.solved && picked && i !== q.answer; return `<button class="choice ${picked ? 'picked' : ''} ${right ? 'right' : ''} ${wrong ? 'wrong' : ''}" data-answer="${i}"><span>${String.fromCharCode(65+i)}</span>${choice}${right ? '<b>정답</b>' : ''}${wrong ? '<b>오답</b>' : ''}</button>` }).join('')}</div>${result?.solved ? `<div class="answer-box ${result.correct ? 'correct' : 'incorrect'}"><strong>${result.correct ? '정답입니다.' : `오답입니다. 정답은 ${String.fromCharCode(65 + q.answer)}입니다.`}</strong><p>${q.explain}</p></div>` : '<div class="answer-hint">선택지를 클릭하면 정답과 해설이 표시됩니다.</div>'}<div class="question-actions">${result?.solved ? '<span class="solved-label">✓ 풀이 기록 저장됨</span>' : '<span>한 문제씩 풀고 해설까지 확인하세요.</span>'}<button class="next-question" data-next>다음 문제 →</button></div></main></div></section>`)
}

function studyDocument(t) {
  const s = sector(t.sector); const base = deepLessons[t.sector]; const detail = topicModules[t.id] || base; const guide = { ...studyGuides[t.sector], ...detail }; const note = state.notes[t.id] || '';
  const layers = detail.layers ? `<div class="layer-table"><div class="layer-head"><span>계층</span><span>무엇을 하나?</span><span>대표 기술·장비</span><span>주요 취약점</span></div>${detail.layers.map((l) => `<div class="layer-row"><b class="layer-number">${l[0]}</b><div><strong>${l[1]}</strong><p>${l[2]}</p></div><div><b>${l[3]}</b><p>${l[4]}</p></div><div><span class="risk-text">${l[5]}</span></div></div>`).join('')}</div>` : '';
  return `<article class="study-document"><div class="study-document-head"><div><span class="eyebrow">${s.en} / ${t.level}</span><h2>${detail.title}</h2><p class="study-lead">${detail.intro}</p></div><div class="study-badge"><span>학습 주제</span><b>${t.title}</b><small>${t.en}</small></div></div><div class="study-callout"><span>핵심 판단</span><p>${detail.important}</p></div>${layers}<div class="study-doc-grid"><div><section class="doc-section"><span class="eyebrow">01 / 이론을 운영 언어로 바꾸기</span><h3>${t.title}에서 꼭 알아야 할 것</h3><p>${guide.core}</p><div class="study-flow">${guide.flow.map((step, i) => `<div class="flow-node"><span>${String(i + 1).padStart(2, '0')}</span><b>${step}</b></div>${i < guide.flow.length - 1 ? '<i class="flow-arrow">→</i>' : ''}`).join('')}</div><p class="diagram-caption">정상 흐름은 <b>${guide.flow.join(' → ')}</b>입니다. 장애나 보안 이벤트가 생기면 이 흐름에서 어느 단계가 달라졌는지부터 확인합니다.</p></section><section class="doc-section"><span class="eyebrow">02 / 운영 순서</span><h3>실무에서 이렇게 확인합니다</h3><ol class="study-steps">${guide.steps.map((step, i) => `<li><b>${i + 1}</b><span>${step}</span></li>`).join('')}</ol></section><section class="doc-section"><span class="eyebrow">03 / 취약점과 실제 상황</span><h3>어떻게 문제가 생기는가</h3><div class="case-list">${guide.cases.map((c, i) => `<div class="case-card"><b>CASE ${String(i + 1).padStart(2, '0')}</b><p>${c}</p></div>`).join('')}</div></section><section class="doc-section"><span class="eyebrow">04 / 대응과 예방</span><h3>운영자가 준비할 통제</h3><ul class="defense-list">${guide.defense.map((d) => `<li><i>✓</i>${d}</li>`).join('')}</ul></section></div><aside class="study-aside"><div class="aside-card"><span class="eyebrow">TERM NOTES</span>${guide.terms.map(([term, desc]) => `<div class="term-item"><b>${term}</b><p>${desc}</p></div>`).join('')}</div><div class="aside-card"><span class="eyebrow">CHECK YOURSELF</span>${t.questions.map((q) => `<p class="question">? ${q}</p>`).join('')}</div><div class="aside-card"><span class="eyebrow">MY NOTES</span><textarea id="topic-note" placeholder="배운 내용을 내 말로 정리하세요...">${esc(note)}</textarea><button class="save-note" id="save-note">메모 저장</button></div><div class="aside-card"><span class="eyebrow">OFFICIAL REFERENCES</span>${[...t.refs, refs[6], refs[7], refs[8], refs[9]].filter((r, i, arr) => r && arr.findIndex((x) => x.name === r.name) === i).map((r) => `<a class="inline-ref" href="${r.url}" target="_blank" rel="noreferrer">${r.name} ↗</a>`).join('')}</div></aside></div><section class="doc-section doc-checks"><span class="eyebrow">05 / 학습 완료 체크</span>${t.checks.map((c, i) => `<label class="modal-check"><input type="checkbox" ${state.completed[`${t.id}-check-${i}`] ? 'checked' : ''} data-check="${t.id}-check-${i}"><span>${c}</span></label>`).join('')}<button class="complete-topic ${state.completed[t.id] ? 'completed' : ''}" id="complete-topic">${state.completed[t.id] ? '✓ 학습 완료됨' : '이 학습을 완료 처리'} <span>→</span></button></section></article>`;
}

function studyPage() {
  const selected = topics.find((t) => t.id === state.selectedTopic) || topics[0];
  return appShell(`<section class="page fade-in study-page"><div class="page-title"><div><span class="eyebrow">STUDY CENTER / THEORY + PRACTICE</span><h1>공부하기</h1><p>팝업 요약이 아니라, 한 주제를 끝까지 읽고 정리하는 실무 교재입니다.</p></div><div class="title-count"><strong>${topics.filter((t) => state.completed[t.id]).length}</strong><span>TOPICS DONE</span></div></div><div class="study-workspace"><aside class="study-nav"><div class="study-nav-title"><span class="eyebrow">COURSE INDEX</span><b>학습 목차</b></div>${sectorMeta.map((s) => `<div class="study-nav-group"><span>${s.icon} ${s.title}</span>${topics.filter((t) => t.sector === s.id).map((t) => `<button class="study-nav-topic ${selected.id === t.id ? 'active' : ''} ${state.completed[t.id] ? 'done' : ''}" data-topic="${t.id}"><i>${state.completed[t.id] ? '✓' : '○'}</i>${t.title}</button>`).join('')}</div>`).join('')}</aside><div class="study-content">${studyDocument(selected)}</div></div></section>`);
}

function references() { return appShell(`<section class="page fade-in"><div class="page-title"><div><span class="eyebrow">PRIMARY SOURCES / VERIFIED LINKS</span><h1>레퍼런스</h1><p>공식 표준·보안기관·제품 문서와 이해하기 쉬운 기술 해설을 함께 연결했습니다.</p></div></div><div class="ref-grid">${refs.map((r,i)=>`<a class="ref-card" href="${r.url}" target="_blank" rel="noreferrer"><div class="ref-index">${String(i+1).padStart(2,'0')}</div><span class="ref-tag">${r.tag}</span><h3>${r.name}</h3><p>${r.desc}</p><div class="ref-foot"><span>${r.org}</span><b>문서 열기 ↗</b></div></a>`).join('')}</div></section>`) }

function render() { const content = state.page === 'dashboard' ? dashboard() : state.page === 'learn' ? learnPage() : state.page === 'study' ? studyPage() : state.page === 'exam' ? examPage() : state.page === 'roadmap' ? roadmap() : state.page === 'matrix' ? matrix() : state.page === 'architecture' ? architecturePage() : references(); document.querySelector('#app').innerHTML = content; bind(); }

const studyGuides = {
  network: { core: '보안 운영자는 장비 이름보다 트래픽의 흐름을 먼저 봅니다. 출발지·목적지·포트·프로토콜·시간을 기준으로 정상 흐름을 만들면 장애와 공격을 빠르게 분리할 수 있습니다.', steps: ['요청을 5-tuple(출발지 IP·목적지 IP·출발지 포트·목적지 포트·프로토콜)로 적기', 'DNS·TCP·TLS·HTTP를 시간순으로 확인하기', '라우팅과 방화벽 정책에서 끊기는 지점 찾기', '서버 로그와 패킷의 시간·상관관계 맞추기', '조치 후 동일 요청으로 복구를 검증하기'], flow: ['사용자', 'DNS', 'TCP/TLS', '보안장비', '서버'], terms: [['5-tuple','한 연결을 구분하는 다섯 가지 네트워크 값'],['SYN','TCP 연결을 시작하는 첫 패킷'],['Baseline','정상 상태에서 관찰되는 기준선']], output: '네트워크 장애 진단서' },
  endpoint: { core: '단말 보안은 설치 여부보다 수집·탐지·판단·격리·복구가 이어지는 운영 생명주기가 핵심입니다. 예외는 편의를 위한 허용이 아니라 만료일이 있는 위험 수용입니다.', steps: ['단말·사용자·업무 중요도 확인하기', '탐지 이벤트의 프로세스·파일·네트워크 행위 확인하기', '오탐·침해·정책 위반을 분류하기', '필요 시 격리하고 증거를 보존하기', '복구 후 정책·예외·재발 방지 검토하기'], flow: ['단말 수집', '탐지 이벤트', '분석/분류', '격리·조치', '복구/개선'], terms: [['EDR','단말 행위를 수집하고 탐지·대응하는 플랫폼'],['IOC','침해를 의심하게 하는 파일·해시·주소 등의 지표'],['NAC','단말 상태에 따라 네트워크 접근을 제어하는 시스템']], output: '단말 탐지 대응 기록' },
  'network-security': { core: '네트워크 보안 장비의 정책은 업무 흐름을 허용하되 과도한 접근을 막는 통제입니다. 모든 변경은 목적·범위·기간·로그·롤백을 함께 가져야 합니다.', steps: ['업무 통신의 출발지·목적지·서비스 정의하기', '최소권한 객체와 정책 순서 설계하기', '로그와 탐지 시그니처를 활성화하기', '테스트 트래픽으로 허용·차단 결과 확인하기', '만료·롤백·사후 검증 일정 기록하기'], flow: ['업무 요청', '정책 설계', '보안장비 검사', '허용/차단', '로그·보고'], terms: [['ACL','주소·포트·방향으로 접근을 허용하거나 차단하는 규칙'],['IPS','공격 패턴을 탐지하고 차단하는 보안 장비'],['WAF','웹 요청을 애플리케이션 앞에서 검사하는 방화벽']], output: '보안 정책 변경서' },
  policy: { core: '정책 운영의 품질은 좋은 규칙보다 좋은 변경 과정에서 나옵니다. 요청을 티켓으로 남기고, 영향도를 검토하고, 승인된 변경만 배포하며, 결과를 증적으로 남깁니다.', steps: ['요청 목적과 업무 영향 수집하기', '중복·과도한 허용·만료 여부 검토하기', '승인자와 테스트 범위 확정하기', '작은 단위로 배포하고 관찰하기', '성공 기준 또는 롤백 조건으로 종료하기'], flow: ['요청/티켓', '검토', '승인', '배포', '검증/롤백'], terms: [['Change','운영 환경에 영향을 주는 통제된 변경'],['Exception','기준 정책에서 한시적으로 벗어나는 승인된 예외'],['Rollback','변경 이전의 검증된 상태로 되돌리는 절차']], output: '정책 변경·승인 기록' },
  incident: { core: '장애 대응은 추측이 아니라 증거의 시간순 정리입니다. 영향 범위를 먼저 줄이고, 서비스 복구와 원인 분석을 분리해 진행한 뒤 재발 방지까지 닫습니다.', steps: ['영향 고객·서비스·시작 시각을 확정하기', '긴급도와 보안성을 기준으로 우선순위 정하기', '최근 변경·로그·지표에서 가설 세우기', '안전한 완화 조치 후 복구 여부 확인하기', '타임라인과 RCA, 액션 아이템 작성하기'], flow: ['알림/문의', '트리아지', '증거 수집', '완화·복구', 'RCA/개선'], terms: [['Triage','영향도와 긴급도로 사건을 분류하는 초기 판단'],['RCA','직접 원인과 근본 원인을 구분하는 분석'],['MTTR','장애 발생부터 복구까지 걸린 평균 시간']], output: '장애 RCA 보고서' },
  customer: { core: 'B2B 운영은 기술 문제를 고객의 업무 영향과 의사결정 언어로 바꾸는 일입니다. 빠른 답변보다 정확한 현재 상태·다음 조치·다음 공유 시각이 신뢰를 만듭니다.', steps: ['고객 표현을 사실·영향·요청으로 나누기', 'SLA 기준과 서비스 중요도로 우선순위 정하기', '확인 중인 가설과 필요한 자료를 명확히 요청하기', '중간 진행 상황과 다음 공유 시각 약속하기', '결과·재발 방지·미결 이슈를 보고서로 남기기'], flow: ['고객 문의', '사실/영향 정리', '기술 분석', '중간 공유', '결과 보고'], terms: [['SLA','응답·복구·공지에 대한 서비스 약속'],['Escalation','담당 범위나 심각도를 넘어 상위 지원으로 올리는 절차'],['KPI','운영 품질과 추세를 측정하는 핵심 지표']], output: 'B2B 운영 보고서' },
  automation: { core: '자동화는 빠르게 실행하는 코드가 아니라 실수를 통제하는 운영 장치입니다. 입력 검증, dry-run, 최소 권한, 감사 로그, 중단과 롤백을 먼저 설계합니다.', steps: ['반복 빈도와 수작업 오류를 측정하기', '자동화할 입력·출력·권한을 제한하기', 'dry-run과 샘플 검증 만들기', '실행 결과·변경 전후·실패를 기록하기', '중단·롤백과 운영자 승인 지점 정하기'], flow: ['운영 요청', '입력 검증', 'Dry-run', '승인 실행', '결과/감사로그'], terms: [['Dry-run','실제 변경 없이 결과만 미리 확인하는 실행'],['Idempotent','같은 작업을 반복해도 결과가 망가지지 않는 성질'],['Audit log','누가 언제 무엇을 실행했는지 남기는 기록']], output: '운영 자동화 설계서' },
  career: { core: '취업 준비의 핵심은 제품명을 나열하는 것이 아니라 문제를 어떻게 판단하고 조치했는지 증명하는 것입니다. 운영 산출물을 면접 답변과 경력기술서의 근거로 사용합니다.', steps: ['채용요건을 경험·지식·산출물로 분해하기', '상황-행동-결과(SAR)로 사례를 고르기', '수치·범위·내 역할·제약조건을 채우기', '정책서·RCA·보고서 형태의 증거 만들기', '기술면접에서 확인 순서와 trade-off 설명하기'], flow: ['채용요건', '경험 분해', '산출물', '성과 수치', '면접 답변'], terms: [['SAR','상황·행동·결과로 경험을 설명하는 구조'],['Trade-off','보안·가용성·운영비용 사이의 판단 균형'],['Portfolio','실무 판단을 보여주는 문서와 결과물 묶음']], output: '경력기술서·운영 포트폴리오' },
}

const deepLessons = {
  network: {
    title: 'TCP/IP 4계층을 한 번에 이해하기',
    intro: 'TCP/IP는 인터넷 통신을 설명하는 실무 모델입니다. 공식 인터넷 아키텍처는 출처에 따라 4계층 또는 링크·인터넷·전송·응용으로 표현하며, OSI 7계층과 일대일로 완전히 같은 모델은 아닙니다.',
    layers: [
      ['1', '네트워크 액세스 (Network Access)', '같은 네트워크 안에서 프레임을 전달합니다.', 'Ethernet, Wi-Fi, ARP, MAC', '스위치·무선 AP·VLAN', 'ARP spoofing, VLAN hopping, 무선 도청, 스위치 포트 무단 접속'],
      ['2', '인터넷 (Internet)', '서로 다른 네트워크 사이에서 패킷의 주소와 경로를 결정합니다.', 'IPv4/IPv6, ICMP, IPsec, BGP', '라우터·L3 스위치', 'IP spoofing, ICMP 악용, 라우팅 조작, 단편화 우회'],
      ['3', '전송 (Transport)', '프로세스와 프로세스 사이의 통신을 포트로 구분합니다.', 'TCP, UDP, QUIC', '방화벽·IPS·로드밸런서', 'SYN flood, 포트 스캔, UDP 증폭, 세션 탈취'],
      ['4', '응용 (Application)', '사용자가 실제로 사용하는 서비스의 규칙과 데이터를 다룹니다.', 'DNS, HTTP/HTTPS, SSH, SMTP, DHCP', 'WAF·프록시·EDR·메일 보안', '인증 우회, 주입, 피싱, 취약한 암호화, 악성 파일 전달'],
    ],
    important: '운영에서 가장 중요한 것은 계층 번호를 외우는 것이 아니라 “어느 계층에서 사실이 끊겼는가”를 찾는 순서입니다. 예를 들어 DNS가 성공했는지, TCP 443 연결이 됐는지, TLS 협상이 끝났는지, HTTP가 200을 반환했는지를 나누어 확인합니다.',
    cases: ['SYN flood: 짧은 시간에 TCP 연결 시작 요청을 대량 전송해 서버의 연결 대기 자원을 소진시키는 유형입니다. 방어는 SYN cookie, 연결 제한, DDoS 보호, 원본 서버 노출 최소화를 조합합니다.', 'ARP spoofing: 같은 L2 네트워크에서 게이트웨이의 MAC 정보를 속여 트래픽을 가로채는 유형입니다. 동적 ARP 검사, DHCP snooping, 네트워크 분리, 암호화 통신으로 위험을 줄입니다.', 'DNS spoofing/cache poisoning: 잘못된 IP를 응답해 사용자를 공격자 서버로 유도합니다. DNSSEC, 재귀 DNS 보안, HTTPS 인증서 검증, DNS 로그 모니터링이 대응책입니다.'],
    defense: ['자산과 정상 통신 기준선 만들기', '방화벽은 필요한 포트만 허용하고 관리 인터페이스를 분리하기', 'TLS·SSH·VPN으로 기밀성과 인증 보장하기', 'IDS/IPS·EDR·DNS·프록시 로그를 시간 기준으로 연결하기', 'CISA KEV와 제조사 보안 공지를 기준으로 패치 우선순위 정하기'],
  },
  endpoint: { title: '단말 보안 솔루션 운영 이론', intro: '단말 보안은 백신 하나를 설치하는 일이 아니라 단말의 상태를 수집하고, 이상 행위를 판단하고, 피해 확산을 막고, 정상 상태로 복구하는 운영 체계입니다.', important: 'EDR은 파일 이름만 보는 도구가 아니라 프로세스 트리·명령줄·사용자·네트워크 연결·지속성(persistence)을 함께 분석합니다. DLP는 데이터 분류와 업무 맥락이 없으면 오탐이 늘고, NAC는 인증과 단말 상태 평가가 핵심입니다.', cases: ['랜섬웨어: 정상 프로세스가 대량 파일 변경을 수행하면 행위 기반 탐지와 호스트 격리로 확산을 차단합니다.', '오탐 예외: 업무 프로그램을 영구 예외 처리하면 탐지 공백이 생깁니다. 해시·경로·서명·기간을 제한하고 만료일과 승인자를 남겨야 합니다.', '감염 단말: 네트워크 격리 전 휘발성 증거와 사용자 영향 범위를 확인하고, 복구 후 재발 방지 정책까지 검토합니다.'], defense: ['에이전트 설치·통신·정책 적용 상태 점검', '탐지 이벤트에서 프로세스 트리와 최초 실행 경로 확인', '격리 전후 증거 보존과 사용자 통지', '예외는 범위·기간·승인자·대체통제를 필수 기록', '복구 후 동일 IOC 재탐지와 정책 회귀 테스트'] },
  'network-security': { title: 'Firewall·IPS·VPN·WAF 이론', intro: '네트워크 보안 장비는 각각 다른 위치에서 다른 판단을 합니다. Firewall은 흐름을 허용·차단하고, IPS는 공격 패턴을 검사하고, VPN은 통신 구간을 보호하고, WAF는 웹 요청의 의미를 검사합니다.', important: '정책을 장비 이름으로 외우기보다 “어떤 트래픽을 어느 지점에서 어떤 근거로 차단하는가”로 이해해야 합니다. 특히 정책 순서, 기본 거부, 로그 활성화, 만료일이 운영 품질을 좌우합니다.', cases: ['any-any 허용: 빠른 장애 조치로 추가된 규칙이 장기간 남아 내부 확산 경로가 될 수 있습니다. 임시 규칙은 만료와 검토 티켓을 갖게 합니다.', 'IPS 오탐: 정상 API가 공격 시그니처에 걸릴 때 원본 요청·룰 ID·반복성을 확인한 뒤 좁은 예외를 적용합니다.', 'VPN 장애: 인증 성공과 내부 서비스 접근 성공은 다릅니다. 인증→터널→주소→라우팅→목적지 정책 순으로 분리합니다.'], defense: ['최소권한·기본거부·정책 순서 검토', '관리 인터페이스 별도 망과 MFA', '정책 변경 전후 로그와 롤백 파일 보존', 'WAF 차단은 룰 ID·요청·원본 응답을 함께 분석', '장비 자체의 취약점은 CISA KEV와 제조사 공지로 우선 조치'] },
  policy: { title: '정책·변경·예외 관리 이론', intro: '정책은 기술 설정이면서 조직의 위험 수용 결정입니다. 좋은 운영은 요청을 기록하고, 영향을 평가하고, 승인하고, 검증하고, 만료시키는 흐름을 반복합니다.', important: '예외는 “허용”이 아니라 정해진 기간 동안의 위험 수용입니다. 정책 이름만 바꾸는 것보다 목적·대상·기간·승인·로그·대체 통제를 남기는 것이 중요합니다.', cases: ['긴급 차단 후 서비스 장애: 긴급 변경도 사유와 승인자, 사후 검토 기한을 남기고 롤백 조건을 정해야 합니다.', '중복 정책: 위쪽의 광범위한 허용 규칙이 아래의 차단 규칙을 무력화할 수 있습니다. 정책 순서와 shadow rule을 점검합니다.', '만료된 예외: 정기 리포트에서 만료 예정·장기 예외·소유자 없는 예외를 분리해 정리합니다.'], defense: ['변경 티켓에 5W1H와 영향 범위 작성', '사전 백업·테스트·성공 기준·롤백 트리거 정의', '승인자와 실행자 분리', '배포 후 로그와 사용자 영향 검증', '예외 만료 리포트와 정기 접근 검토'] },
  incident: { title: '로그 분석과 장애 대응 이론', intro: '사고 대응은 알람에 반응하는 일이 아니라 증거를 보존하고, 영향 범위를 줄이고, 서비스를 복구하고, 원인을 설명하는 과정입니다.', important: 'NIST 사고 대응 흐름을 실무적으로 적용하면 준비→탐지·분석→대응→복구→사후 개선으로 이어집니다. 장애와 보안사고를 처음부터 완벽히 구분하려 하지 말고, 사실과 가설을 분리해 기록해야 합니다.', cases: ['로그 시간 불일치: NTP가 맞지 않으면 공격 타임라인이 뒤섞입니다. 수집기·장비·서버의 시간 오차를 먼저 확인합니다.', '알람 폭증: 동일 원인의 중복 이벤트를 묶고 영향도·확산성·자산 중요도로 우선순위를 조정합니다.', 'RCA 실패: “담당자 실수”로 끝내지 말고 직접 원인·기여 요인·탐지 실패·프로세스 개선을 나눠 작성합니다.'], defense: ['영향 범위·시작 시각·최근 변경 확인', '원본 로그와 증거 보존', '완화 조치와 원인 분석을 병렬로 진행', '복구 후 같은 증상 재현·검증', 'RCA에 담당자·기한·측정 가능한 개선 항목 포함'] },
  customer: { title: 'B2B 고객 보안 운영 이론', intro: 'B2B 솔루션 운영자는 기술자이면서 서비스 운영자입니다. 고객이 이해할 수 있는 영향과 다음 조치를 설명하고, 약속한 시각에 상태를 업데이트해야 합니다.', important: '고객 문의를 “증상·영향·원하는 조치”로 재작성하면 조사 방향이 선명해집니다. 기술적으로 맞는 말도 고객 업무 영향과 연결되지 않으면 좋은 운영 보고가 아닙니다.', cases: ['전체 장애처럼 보이는 단일 사용자 문제: 사용자·단말·망·정책 범위를 분리해 실제 영향도를 좁힙니다.', 'SLA 임박 장애: 기술 분석과 별개로 현재 상태·완화책·다음 공지 시각을 먼저 공유합니다.', '월간 탐지 증가: 단순 건수 대신 자산 중요도·심각도·처리 시간·재발 여부로 추세를 설명합니다.'], defense: ['접수 시각·영향·범위·재현 절차 기록', 'SLA 응답·복구·공지 기준 확인', '가설과 확인 중인 항목을 고객에게 구분해서 전달', '회의록에 결정·담당·기한·미결 이슈 기록', '정기 보고에 위험·추세·개선 결과 포함'] },
  automation: { title: '보안 운영 자동화 이론', intro: '보안 자동화는 권한이 큰 시스템을 빠르게 바꾸므로 일반 업무 자동화보다 안전장치가 더 중요합니다. 자동화 전후의 상태를 비교할 수 있어야 합니다.', important: '가장 먼저 자동화할 대상은 반복 빈도가 높고 규칙이 명확하며 실패 시 복구 가능한 작업입니다. 고위험 차단·삭제·대량 정책 변경은 승인과 dry-run을 남겨야 합니다.', cases: ['대량 정책 오타: 입력 검증과 샘플 실행 없이 전체 배포하면 서비스 장애가 발생합니다.', '자동화 계정 탈취: 최소 권한·시크릿 관리·실행 IP 제한·감사 로그로 피해 범위를 줄입니다.', '보고 자동화 오탐: 집계 기준과 중복 제거 규칙을 문서화하지 않으면 잘못된 KPI가 만들어집니다.'], defense: ['dry-run과 입력 스키마 검증', '최소 권한 서비스 계정과 시크릿 분리', '실행 전 승인·실행 후 결과 검증', '실패 시 중단·롤백·수동 전환', '코드 변경 리뷰와 테스트 로그 보존'] },
  career: { title: '정보보안기사·취업 이론 연결법', intro: '자격증 이론은 암기장으로 끝내지 말고 운영 상황에 연결해야 합니다. 네트워크·시스템·애플리케이션·관리체계의 개념을 실제 정책·로그·장애 사례로 설명하는 연습이 필요합니다.', important: '면접에서는 “무엇인가”보다 “어디서 확인하고, 왜 그렇게 판단하며, 어떻게 재발을 막는가”가 중요합니다. 모든 학습 주제를 하나의 운영 산출물로 바꾸면 경력 공백을 학습 결과로 설명할 수 있습니다.', cases: ['TCP/IP 질문: 4계층을 말한 뒤 DNS→TCP→TLS→HTTP 확인 순서를 장애 사례로 연결합니다.', '취약점 질문: CVE 번호 암기보다 영향 자산·악용 가능성·패치·완화·검증을 설명합니다.', '고객 대응 질문: 기술 조치와 함께 현재 상태·예상 시각·다음 공지 약속을 말합니다.'], defense: ['정보보안기사 과목을 8개 운영 섹터에 매핑', '한 주제마다 1쪽 요약과 1개 실습 산출물 작성', 'SAR 또는 STAR 구조로 경험 답변 정리', '공식 문서와 최신 취약점 공지 확인 습관화', '모르는 내용은 확인 경로와 검증 방법까지 답변'] },
}

const makeModule = (title, intro, important, flow, cases, defense, terms) => ({ title, intro, important, core: important, flow, cases, defense, terms });
const topicModules = {
  'network-1': makeModule('TCP/IP 4계층과 보안 경계', 'TCP/IP는 인터넷 통신을 네 개의 책임 영역으로 나누어 보는 실무 모델입니다. OSI 7계층과 이름을 억지로 일치시키기보다 패킷이 어디에서 만들어지고 어디에서 통제되는지 이해해야 합니다.', '장애 분석의 시작은 계층 암기가 아니라 정상 흐름의 기준선입니다. DNS 성공, TCP 연결, TLS 협상, HTTP 응답을 분리하면 “네트워크 문제”라는 모호한 말을 구체적인 증거로 바꿀 수 있습니다.', ['애플리케이션 요청', 'DNS/주소 해석', 'TCP·TLS 연결', 'IP 라우팅·정책', 'Ethernet 전달'], ['ARP spoofing은 같은 L2 망에서 게이트웨이를 사칭해 트래픽을 가로챌 수 있습니다.', 'IP spoofing은 출발지 주소를 속이므로 인증을 IP만으로 신뢰하면 안 됩니다.', 'SYN flood는 연결 대기 자원을 소진하므로 SYN cookie와 연결 제한을 검토합니다.'], ['VLAN·망분리와 동적 ARP 검사', '방화벽 기본 거부와 관리망 분리', 'TLS·SSH·VPN으로 상위 계층 인증·암호화', 'NTP와 패킷·장비·서버 로그 상관분석'], [['L2','같은 망의 프레임 전달','Ethernet·ARP·MAC'],['L3','망 사이의 주소·경로','IPv4/IPv6·ICMP·라우터'],['L4','프로세스 간 통신','TCP·UDP·포트'],['L7','서비스 데이터 규칙','DNS·HTTP·SSH']]),
  'network-2': makeModule('DNS와 HTTP 흐름을 끝까지 추적하기', '브라우저에 주소를 입력하면 먼저 DNS가 이름을 IP로 바꾸고, 이후 TCP 또는 QUIC/TLS 연결과 HTTP 요청이 이어집니다. 각 단계의 성공은 다음 단계의 성공을 보장하지 않습니다.', 'DNS는 재귀 리졸버·권한 서버·캐시의 관계를, HTTP는 메서드·헤더·상태코드·본문의 관계를 따로 봅니다. 보안 운영자는 URL 하나를 요청/응답 로그와 DNS 질의 로그로 재구성할 수 있어야 합니다.', ['브라우저 캐시', '재귀 DNS 질의', 'TCP 3-way/TLS', 'HTTP 요청', '상태코드·응답'], ['DNS cache poisoning은 잘못된 IP를 캐시에 넣어 피싱 사이트로 유도할 수 있습니다.', 'HTTP 301/302 리다이렉트가 악성 도메인으로 연결되는지 확인해야 합니다.', 'HTTP 200이어도 응답 본문이 악성 파일이거나 인증이 우회됐을 수 있어 상태코드만 신뢰하면 안 됩니다.'], ['DNSSEC·안전한 재귀 DNS·DNS 로그 모니터링', 'HTTPS 인증서·SNI·호스트 헤더 검증', 'WAF·프록시에서 메서드·URI·파라미터 기록', '브라우저·프록시·서버의 상관관계 ID 연결'], [['DNS','이름을 IP로 바꾸는 질의 체계','A/AAAA·CNAME·TTL'],['HTTP','웹 요청·응답 규칙','메서드·헤더·상태코드'],['TLS','통신 상대 인증과 암호화','인증서·SNI·핸드셰이크']]),
  'network-3': makeModule('라우팅과 방화벽 기초', '라우팅은 목적지까지의 다음 홉을 고르는 일이고 방화벽은 그 흐름을 정책으로 허용하거나 차단하는 일입니다. 경로가 있어도 정책이 막을 수 있고, 정책이 허용해도 경로가 없으면 통신되지 않습니다.', '장애 분석에서는 라우팅 테이블, 보안 정책, NAT, 반환 경로를 분리합니다. 특히 비대칭 라우팅과 상태 추적 방화벽은 “한 방향은 보이는데 응답이 안 오는” 증상을 만들 수 있습니다.', ['목적지 조회', '다음 홉 선택', 'NAT 변환', '방화벽 상태 확인', '응답 경로 확인'], ['잘못된 정적 경로는 특정 대역만 타임아웃을 만들 수 있습니다.', 'NAT 후 로그의 원본 주소가 달라져 조사자가 잘못된 자산을 추적할 수 있습니다.', '상태 추적 장비에서 비대칭 경로는 정상 응답을 비정상 세션으로 판단하게 할 수 있습니다.'], ['정책 전 출발지·목적지·포트·방향 기록', '양방향 라우팅과 NAT 전후 주소 비교', '정책 hit count와 deny 로그 확인', '변경 후 테스트 트래픽과 롤백 기준 기록'], [['Route','목적지로 가는 다음 홉 정보','Longest prefix match'],['NAT','주소·포트를 변환하는 기능','SNAT·DNAT·PAT'],['Stateful','세션 상태를 기억하는 방화벽','5-tuple·세션 테이블']]),
  'network-4': makeModule('패킷·로그 읽기', '패킷은 통신의 사실을, 로그는 장비가 해석한 사건을 보여줍니다. 둘을 함께 보면 “차단되었다”는 결과를 정책 차단인지 서버 거부인지 구분할 수 있습니다.', '분석 순서는 시간창을 정한 뒤 5-tuple, TCP 플래그, 재전송, 응답 코드, 장비 로그를 맞추는 것입니다. 캡처 한 장을 보고 공격으로 단정하지 말고 반복성과 자산 맥락을 확인합니다.', ['시간창 설정', '5-tuple 필터', 'TCP 플래그 확인', '장비 로그 대조', '가설 검증'], ['SYN만 반복되면 스캔·장애·공격을 구분하기 위해 원본 IP 분포와 포트 범위를 봅니다.', 'TCP 재전송은 네트워크 손실뿐 아니라 서버 응답 지연에서도 발생합니다.', '로그 누락은 정상이라는 증거가 아니므로 수집기와 보존 상태를 함께 점검합니다.'], ['NTP·타임존 통일', '원본 PCAP과 원본 로그 보존', '패킷·방화벽·서버 로그의 공통 키 사용', '분석 결과에 사실·가설·확인 방법을 분리 기록'], [['5-tuple','주소와 포트로 연결 구분','src/dst IP·port·protocol'],['Flag','TCP 상태를 나타내는 비트','SYN·ACK·RST·FIN'],['PCAP','패킷 원본 캡처','재현·증거 보존']]),
  'endpoint-1': makeModule('EDR 운영 모델', 'EDR은 단말의 프로세스·파일·레지스트리·로그인·네트워크 행위를 수집해 탐지와 대응으로 연결하는 플랫폼입니다. 백신의 정적 탐지보다 사건의 맥락과 행위 연쇄가 중요합니다.', '하나의 경보를 사건으로 확장하려면 최초 실행 파일, 부모-자식 프로세스, 사용자, 호스트 중요도, 외부 통신을 함께 봅니다.', ['텔레메트리 수집', '경보 생성', '프로세스 트리 분석', '격리·증거수집', '복구·재탐지 확인'], ['Office 문서에서 PowerShell이 실행되고 외부 C2로 연결되는 행위는 파일명보다 행위 연결이 중요합니다.', '동일 IOC가 여러 호스트에서 보이면 단말 단위가 아닌 확산 사건으로 승격합니다.'], ['심각도·자산 중요도·사용자 영향을 함께 평가', '격리 전 증거 보존과 업무 영향 확인', 'IOC 차단·취약점 패치·자격증명 재설정', '복구 후 동일 행위 재탐지와 헌팅'], [['Telemetry','단말에서 수집되는 행위 데이터','process·file·network'],['Process tree','부모-자식 실행 계보','경로·명령줄·사용자'],['IOC','침해 지표','hash·domain·IP']]),
  'endpoint-2': makeModule('백신 정책과 예외', '백신 운영은 탐지율만 높이는 일이 아니라 실시간 보호, 검사 주기, 업데이트, 예외 범위를 업무 영향과 함께 조정하는 일입니다.', '예외는 탐지를 끄는 버튼이 아니라 통제된 위험 수용입니다. 서명·해시·경로·프로세스·기간 중 가장 좁은 조건을 선택하고 만료 후 재검토합니다.', ['오탐 접수', '파일·서명 검증', '업무 영향 평가', '제한적 예외', '만료·재검토'], ['서명된 업무 프로그램도 공급망이 훼손되면 악용될 수 있어 서명만으로 영구 신뢰하지 않습니다.', '전체 폴더 예외는 악성 파일이 같은 경로에 들어올 수 있는 큰 탐지 공백입니다.'], ['샘플 격리·다중 엔진 검증', '예외 티켓에 사유·범위·기간·승인자 기록', '대체 통제와 탐지 룰 보강', '예외 만료 리포트와 회귀 테스트'], [['Real-time','파일 실행·접근 순간 검사','악성 행위 차단'],['Signature','알려진 패턴 기반 탐지','업데이트 주기 중요'],['Exclusion','검사를 제외하는 조건','범위·기간 최소화']]),
  'endpoint-3': makeModule('DLP 데이터 흐름', 'DLP는 누가 어떤 데이터를 어떤 채널로 이동했는지 통제합니다. 먼저 데이터 분류와 업무 맥락을 정해야 정상 반출과 유출을 구분할 수 있습니다.', '파일명보다 주민번호·소스코드·계약서 같은 콘텐츠 식별자, 사용자·부서·목적지·채널·시간을 함께 평가해야 합니다.', ['데이터 분류', '채널 감시', '행위 탐지', '사용자 확인', '차단·승인·보고'], ['USB로 대량 복사했지만 승인된 백업일 수 있으므로 단순 차단보다 업무 목적과 승인 기록을 확인합니다.', '압축·암호화·화면 촬영은 일반 파일 검사만으로 놓칠 수 있어 행위와 채널을 결합해야 합니다.'], ['민감도 라벨과 정책 연결', 'USB·메일·웹 업로드별 최소권한', '차단 전 사용자·관리자 승인 흐름', '오탐·정탐 샘플을 정기적으로 재학습'], [['Data classification','정보 중요도 분류','공개·내부·기밀'],['Channel','데이터 이동 경로','USB·메일·웹·클라우드'],['Exfiltration','승인되지 않은 반출','대량·비정상·외부 목적지']]),
  'endpoint-4': makeModule('NAC 접근제어', 'NAC는 사용자가 인증했는지뿐 아니라 접속 단말이 보안 기준을 만족하는지 평가해 네트워크 접근을 결정합니다.', '인증 실패, 단말 비준수, 스위치 포트 문제, RADIUS 통신 문제를 구분해야 합니다. 격리망 이동 후 정상 복귀 조건도 정책에 포함해야 합니다.', ['단말 접속', '802.1X/RADIUS 인증', '상태 평가', '정상·격리 VLAN', '보완 후 복귀'], ['패치가 오래된 단말이 인증은 성공하지만 비준수 판정을 받아 격리망에 들어갈 수 있습니다.', 'NAC 서버와 스위치 간 RADIUS 타임아웃은 사용자 비밀번호 문제처럼 보일 수 있습니다.'], ['인증·상태평가·VLAN 할당 로그 상관분석', '예외 단말은 MAC 고정이 아닌 소유자·기간·보완통제 기록', '격리망에서도 업데이트·관리 서버만 허용', '복귀 후 정책 재평가와 테스트'], [['802.1X','포트 기반 네트워크 접근 인증','supplicant·authenticator·RADIUS'],['Posture','단말 보안 상태','패치·에이전트·암호화'],['Quarantine VLAN','비준수 단말 격리 망','복구용 최소 통신']]),
  'network-security-1': makeModule('Firewall 정책 설계', '방화벽 규칙은 업무 통신을 표현한 통제 문장입니다. 출발지·목적지·서비스·방향·기간·로그를 명확히 해야 합니다.', '정책 순서와 기본 거부가 실제 보안 수준을 결정합니다. 광범위한 허용 규칙이 위에 있으면 아래의 세밀한 차단 규칙은 도달하지 못합니다.', ['업무 흐름 수집', '객체·서비스 정의', '최소 허용 작성', '테스트·로그 확인', '만료·정리'], ['any-any 규칙은 장애를 즉시 해결해도 내부 확산·관리면 노출 위험을 키웁니다.', '정책 객체에 오래된 IP가 남으면 의도하지 않은 시스템이 허용 범위에 들어갑니다.'], ['정책 리뷰와 shadow rule 점검', '신규·변경·삭제 모두 티켓화', 'hit count·deny 로그로 사후 검증', '임시 규칙 만료일과 소유자 지정'], [['Rule order','상위 규칙부터 평가되는 순서','shadowing·first match'],['Object','주소·서비스를 이름으로 묶은 객체','변경 영향 관리'],['Implicit deny','명시적으로 허용되지 않은 흐름 차단','최소권한 기본값']]),
  'network-security-2': makeModule('IPS 탐지와 예외', 'IPS는 트래픽의 패턴과 문맥을 검사해 공격 시그니처를 탐지·차단합니다. 시그니처가 맞더라도 업무 정상 트래픽과 구분하는 검증이 필요합니다.', '예외는 룰 전체를 끄는 것이 아니라 출발지·목적지·URI·기간을 좁혀 적용해야 합니다. 탐지 이벤트 원문과 룰 버전을 증거로 남깁니다.', ['시그니처 탐지', '원본 요청 확인', '정탐·오탐 판정', '좁은 예외·완화', '재현·검증'], ['정상 API JSON 값이 SQLi 시그니처와 유사해 차단될 수 있습니다.', '오래된 시그니처는 우회 공격을 놓칠 수 있어 엔진 업데이트와 탐지 공백을 함께 확인합니다.'], ['원본 페이로드·룰 ID·대상 자산 확인', '예외 전 애플리케이션 수정 가능성 검토', '예외 만료와 모니터링 룰 유지', '정탐 샘플로 차단이 계속 작동하는지 검증'], [['Signature','공격 패턴 규칙','룰 ID·버전·심각도'],['False positive','정상 행위를 공격으로 판단','좁은 예외·애플리케이션 수정'],['Inline','트래픽 경로에서 즉시 차단','장애 영향·fail-open/close']]),
  'network-security-3': makeModule('VPN 인증과 터널', 'VPN은 사용자 인증, 암호화 터널, 가상 주소, 라우팅, 내부 정책이 모두 맞아야 업무 접속이 됩니다.', '“로그인 성공”과 “업무 시스템 접속 성공”을 분리합니다. MFA·인증서·IP 풀·split tunnel·DNS 정책을 각각 확인해야 합니다.', ['인증/MFA', '터널 협상', '가상 IP 할당', '라우팅·DNS', '목적지 정책'], ['인증은 성공하지만 IP 풀 고갈로 내부 주소를 받지 못할 수 있습니다.', '전체 터널 강제 정책은 보안은 높일 수 있지만 보안 에이전트·업데이트 통신을 막을 수 있습니다.'], ['클라이언트·게이트웨이 양쪽 협상 로그 확인', '사용자·시간·출발지·가상 IP로 세션 추적', '분할 터널과 보안 예외를 문서화', '장애 조치 후 내부·외부 경로를 각각 테스트'], [['IKE','IPsec 터널 협상 프로토콜','Phase 1/2·암호군'],['MFA','다중 요소 인증','계정 탈취 완화'],['Split tunnel','일부 트래픽만 VPN 통과','보안·성능 trade-off']]),
  'network-security-4': makeModule('WAF 요청 분석', 'WAF는 웹 애플리케이션 앞에서 HTTP 요청을 검사합니다. URI·메서드·헤더·쿠키·파라미터·본문과 원본 서버 응답을 함께 봐야 합니다.', '403은 WAF 차단일 수도 있고 애플리케이션 인증 실패일 수도 있습니다. 룰 ID와 원본 요청을 대조해 좁은 예외 또는 코드 수정을 선택합니다.', ['클라이언트 요청', 'WAF 정규화', '룰 평가', '허용·차단', '원본 응답·로그'], ['SQL injection·XSS·경로 조작 패턴은 WAF에서 탐지할 수 있지만 애플리케이션 취약점 자체를 고치는 대체재는 아닙니다.', '인코딩·대소문자·중첩 JSON으로 탐지를 우회하려는 요청을 정규화와 애플리케이션 검증으로 방어합니다.'], ['룰 ID·요청 ID·원본 응답을 묶어 분석', '정상 요청은 URI·파라미터 단위로 좁은 예외', '개발팀의 입력 검증·출력 인코딩 수정', '차단·탐지 모드 전환 후 재현 테스트'], [['WAF','웹 요청 전용 방화벽','HTTP 문맥 검사'],['Normalization','인코딩·공백 등을 표준화','우회 탐지 완화'],['Origin','WAF 뒤 실제 애플리케이션','직접 노출 금지']]),
  'policy-1': makeModule('정책 배포 절차', '보안 정책 배포는 요청을 설정값으로 번역하는 변경관리 작업입니다. 기술적으로 맞는 규칙도 업무 영향과 검증 기준이 없으면 운영 실패가 됩니다.', '변경 전후 상태를 재현할 수 있도록 티켓·승인·백업·테스트·관찰시간·종료 기준을 한 세트로 남깁니다.', ['요청·목적 정의', '영향 분석', '승인·백업', '단계적 배포', '사후 검증'], ['긴급 차단 규칙이 정상 결제 트래픽까지 막을 수 있어 business owner 확인과 rollback 기준이 필요합니다.', '정책은 성공 메시지가 떠도 실제 서비스 로그에서 효과를 검증해야 합니다.'], ['정책 diff와 백업 파일 보관', 'change window와 담당자 이중 확인', '성공 기준·롤백 trigger 명시', '배포 후 고객·모니터링 로그 확인'], [['Change ticket','변경 목적과 이력 기록','승인·영향·결과'],['Rollback','이전 정상 상태 복원','조건·담당자·백업'],['Validation','변경 효과 검증','로그·서비스 테스트']]),
  'policy-2': makeModule('예외 승인 관리', '예외는 정책을 무시하는 편의가 아니라 통제되지 않은 위험을 일정 기간 받아들이는 공식 결정입니다.', '예외 요청을 자산·위협·업무 필요·대체 통제·만료일로 구조화하면 승인자가 위험을 비교할 수 있습니다.', ['예외 요청', '위험 평가', '보완통제 설정', '승인·등록', '만료·재검토'], ['개발 서버의 백신 예외가 운영 서버로 복사되어 탐지 공백이 생길 수 있습니다.', '만료된 방화벽 허용이 남아 있으면 현재 업무 필요와 무관한 공격면이 됩니다.'], ['예외 범위 최소화', '소유자·승인자·만료일 필수화', '대체 로그·모니터링 적용', '만료 전 자동 알림과 미갱신 회수'], [['Risk acceptance','잔여 위험을 승인하는 결정','승인권자·기간'],['Compensating control','예외를 보완하는 통제','모니터링·제한'],['Expiry','예외가 끝나는 시점','자동 회수·재검토']]),
  'policy-3': makeModule('변경·롤백', '운영 변경은 성공보다 실패했을 때 얼마나 안전하게 되돌릴 수 있는지가 중요합니다. 롤백은 “문제가 생기면 생각해보자”가 아니라 실행 가능한 절차여야 합니다.', '롤백 기준은 서비스 오류율·보안 로그·고객 영향처럼 관찰 가능한 지표로 정하고, 복구 후 원인 분석과 재배포 여부를 분리합니다.', ['변경 전 기준선', '작은 범위 실행', '관찰 지표 확인', '롤백 또는 확대', '변경 종료'], ['정책 변경 직후 특정 고객만 접속 실패하면 전체 롤백보다 해당 객체를 우선 분리하는 것이 안전할 수 있습니다.', '롤백 파일 자체가 최신 상태를 덮어쓸 수 있어 변경 전 백업과 버전 식별이 필요합니다.'], ['canary·단계적 배포', '관찰시간과 abort 기준 사전 정의', '롤백 실행자와 승인자 지정', '변경 후 configuration drift 점검'], [['Canary','일부 범위에 먼저 적용','영향 최소화'],['Abort criteria','중단을 결정하는 객관 기준','오류율·영향'],['Drift','승인 상태와 실제 설정 차이','정기 비교']]),
  'policy-4': makeModule('SOP와 증적', 'SOP는 특정 담당자가 없어도 같은 품질로 처리하게 만드는 운영 지식입니다. 증적은 그 절차가 실제로 수행됐음을 보여주는 기록입니다.', '좋은 SOP는 목적·사전조건·절차·예외·검증·에스컬레이션·보존기간을 포함하고, 문서 버전과 소유자를 가집니다.', ['업무 정의', '사전 조건', '표준 절차', '예외 처리', '결과 증적'], ['문서에만 “정기 점검”이라고 쓰고 실제 실행 로그가 없으면 감사와 장애 재현 모두 어려워집니다.', '오래된 SOP가 최신 제품 UI와 다르면 운영자가 잘못된 조치를 수행할 수 있습니다.'], ['문서 owner와 review date 관리', '실행 티켓·로그·스크린샷·결과 연결', '분기별 tabletop 또는 dry-run', '변경 시 SOP 동시 개정'], [['SOP','표준 운영 절차서','재현 가능한 작업'],['Evidence','수행 결과를 입증하는 기록','티켓·로그·승인'],['Review date','문서 재검토 예정일','현행성 관리']]),
  'incident-1': makeModule('로그 수집과 기준선', '로그는 보안 판단의 원재료입니다. 무엇을 수집할지보다 시간·필드·보존·무결성·누락을 먼저 설계해야 합니다.', '정상 기준선은 평균값 하나가 아니라 사용자·자산·시간대별 반복 패턴입니다. 기준선이 있어야 “평소와 다름”을 설명할 수 있습니다.', ['로그 소스 식별', 'NTP 동기화', '필드 표준화', '정상 기준선', '누락·변조 점검'], ['로그 시간이 9분만 어긋나도 로그인→권한상승→파일전송 순서가 바뀌어 분석을 오판할 수 있습니다.', '수집기는 살아 있어도 특정 필드가 파싱되지 않으면 탐지 룰이 조용히 실패할 수 있습니다.'], ['NTP·타임존 표준화', '수집 성공률과 필드 품질 모니터링', '원본 로그와 정규화 로그 보존', '로그 접근권한·무결성·보존기간 관리'], [['Baseline','정상 상태의 관찰 기준','시간대·자산·사용자'],['Normalization','로그 필드와 형식 통일','파싱·상관분석'],['Retention','로그를 보존하는 기간','법규·사고조사']]),
  'incident-2': makeModule('장애 트리아지', '트리아지는 모든 문제를 한 번에 해결하는 과정이 아니라 영향과 긴급도를 판단해 올바른 대응자를 연결하는 과정입니다.', '보안성·확산성·서비스 영향·자산 중요도를 함께 보고, 현재 확인된 사실과 아직 검증하지 않은 가설을 분리합니다.', ['접수·알림', '영향 범위', '심각도 분류', '담당 배정', '중간 공지'], ['단일 사용자의 에이전트 장애와 전사 정책 배포 실패는 같은 “접속 안 됨”이라도 우선순위가 다릅니다.', '알람 건수가 많아도 동일 원인의 중복 이벤트라면 사건 하나로 묶어야 합니다.'], ['P1~P4 등급과 SLA 연결', '고객 영향과 보안 위험을 각각 기록', '에스컬레이션 조건 명시', '다음 공지 시각을 약속하고 지키기'], [['Severity','기술·보안 심각도','영향·확산·자산'],['Priority','처리 순서','긴급도·SLA'],['Escalation','상위 지원으로 전환','조건·담당·시각']]),
  'incident-3': makeModule('원인 분석 RCA', 'RCA는 “누가 잘못했나”가 아니라 왜 시스템과 절차가 실패를 막지 못했는지를 찾는 문서입니다.', '증상, 직접 원인, 기여 요인, 탐지 실패, 근본 원인, 재발 방지책을 시간순 증거와 함께 연결합니다.', ['타임라인 작성', '증거 수집', '가설 세우기', '재현·반증', '개선 액션'], ['정책 변경 뒤 장애가 났더라도 실제 직접 원인은 오래된 객체와 누락된 회귀 테스트일 수 있습니다.', '“설정 오류”로 끝내면 승인·검증·모니터링의 실패가 반복됩니다.'], ['5 Whys와 fault tree 활용', '사실·추정·미확인 항목 구분', '액션에 owner·기한·측정값 부여', '개선 후 동일 시나리오 재시험'], [['Timeline','사건을 시간순으로 배열','변경·알람·조치'],['Root cause','반복을 막는 근본 요인','통제·절차·설계'],['Action item','재발 방지 실행 항목','owner·due date·metric']]),
  'incident-4': makeModule('사고 후 개선', '복구가 끝난 시점은 사고 대응의 끝이 아니라 조직이 다음 사고를 더 빨리 발견하고 작게 끝내도록 바꾸는 시작점입니다.', '사고 후 검토는 탐지·대응·복구·소통·문서의 다섯 관점에서 측정 가능한 개선을 남겨야 합니다.', ['복구 확인', '사후 검토', '통제 공백', '개선 우선순위', '재훈련·검증'], ['같은 IOC가 반복되면 탐지 룰보다 자산 식별·패치·권한 관리의 공백을 먼저 재평가해야 합니다.', '사고 보고서가 보관만 되고 tabletop으로 검증되지 않으면 실제 대응 능력은 변하지 않습니다.'], ['MTTD·MTTR·재발률 추적', '탐지 룰·SOP·교육 동시 개선', 'high-risk 액션 우선 처리', 'tabletop과 복구 훈련으로 검증'], [['Lessons learned','사고에서 얻은 개선점','비난 없는 검토'],['MTTD','탐지까지 걸린 시간','센서·모니터링'],['MTTR','복구까지 걸린 시간','절차·자동화']]),
  'customer-1': makeModule('B2B 이슈 접수', '고객의 “보안 솔루션이 안 돼요”라는 표현을 기술자가 조사할 수 있는 사건으로 번역하는 첫 단계입니다.', '접수 양식은 발생 시각, 영향 사용자·서비스, 재현 절차, 최근 변경, 오류 메시지, 첨부 로그를 포함해야 합니다.', ['고객 표현', '사실·영향 분리', '재현 정보', '초기 안내', '티켓 생성'], ['전체 장애라고 접수됐지만 실제로는 특정 VLAN의 단말 정책 미적용인 경우가 많아 범위 확인이 먼저입니다.', '고객이 보낸 로그에는 민감정보가 포함될 수 있으므로 수집·보관 권한을 제한합니다.'], ['초기 응답에서 현재 상태와 다음 확인 항목 공유', '민감정보 마스킹 요청', '티켓에 customer impact와 technical symptom 분리', 'SLA 시각 자동 기록'], [['Impact','고객 업무에 미친 영향','사용자·서비스·범위'],['Reproduce','같은 증상을 다시 만드는 절차','조건·시각·계정'],['Ticket','이슈의 단일 기록','소유자·SLA·이력']]),
  'customer-2': makeModule('SLA와 우선순위', 'SLA는 단순히 빨리 답하라는 약속이 아니라 응답·복구·중간 공지·에스컬레이션을 운영 기준으로 정한 것입니다.', '기술 심각도와 고객 서비스 중요도를 곱해 우선순위를 판단합니다. 단일 사용자라도 핵심 관리자 계정이면 위험도가 높을 수 있습니다.', ['심각도 확인', '고객 중요도', 'SLA 시계 시작', '담당·에스컬레이션', '공지 주기'], ['낮은 건수의 인증 장애가 결제·생산 시스템을 막으면 일반 문의보다 높은 우선순위가 됩니다.', '응답만 빨리 하고 다음 공지 약속을 지키지 않으면 기술 조치가 끝나도 신뢰를 잃습니다.'], ['SLA별 템플릿과 연락망 관리', '현재 상태·다음 시각·담당자 명시', '지연 예측 시 조기 에스컬레이션', '사후 SLA 원인과 개선 보고'], [['SLA clock','응답·복구 기준 시간','시작·중지 조건'],['Criticality','서비스·자산 중요도','업무 영향'],['Escalation matrix','심각도별 연락 체계','담당·백업·관리자']]),
  'customer-3': makeModule('기술 협의 진행', '기술 협의는 회의에서 많이 말하는 것이 아니라 서로 다른 가정을 결정사항과 실행계획으로 고정하는 일입니다.', '아젠다·현재 상태·선택지·보안 영향·결정권자·액션·기한을 문서화하면 고객과 운영팀의 재해석을 줄일 수 있습니다.', ['아젠다 공유', '현재 사실 정리', '선택지 비교', '결정·승인', '회의록·추적'], ['방화벽 허용 요청이 보안팀에는 큰 범위로 보이고 고객에는 긴급 업무로 보일 수 있어 대안별 위험을 비교해야 합니다.', '회의에서 합의했어도 티켓과 승인 기록이 없으면 실행 책임이 불명확해집니다.'], ['비기술 용어로 영향 설명', '결정사항과 미결 이슈 분리', '액션 owner·due date 기록', '다음 회의 전 미결 이슈 검증'], [['Agenda','회의에서 결정할 항목','목표·범위'],['Decision log','결정과 근거 기록','대안·승인자'],['Action owner','실행 책임자','기한·완료 기준']]),
  'customer-4': makeModule('정기 운영 보고', '정기 보고는 처리 건수를 나열하는 문서가 아니라 고객의 위험이 어떻게 변했고 다음 달 무엇을 할지 보여주는 운영 산출물입니다.', '탐지량·처리시간·미해결 위험·예외·정책 변경·재발률을 추세로 보여주고, 수치 변화의 원인과 조치를 함께 설명합니다.', ['데이터 집계', '품질 검증', '추세 분석', '위험·조치 작성', '고객 리뷰'], ['탐지 건수 증가가 공격 증가가 아니라 센서 범위 확대일 수 있어 지표 정의와 변경사항을 함께 표시해야 합니다.', '미해결 위험을 숨기면 단기 평가는 좋아 보여도 사고 시 신뢰가 무너집니다.'], ['KPI 정의서와 분모 관리', '심각도·자산 중요도별 분리', '미해결 위험 owner와 기한 기록', '전월 대비 변화와 다음 계획 제시'], [['KPI','운영 품질 지표','정의·분모·추세'],['Backlog','아직 닫히지 않은 이슈','age·priority·owner'],['Trend','시간에 따른 변화','원인·조치·예측']]),
  'automation-1': makeModule('운영 자동화 원칙', '보안 자동화는 권한이 큰 작업을 반복하므로 편의보다 안전한 실패와 감사 가능성을 우선합니다.', '자동화 후보는 빈도가 높고 규칙이 명확하며 실패 시 수동 복구가 가능한 작업부터 선정합니다.', ['대상 선정', '위험 평가', 'dry-run', '승인 실행', '결과·롤백'], ['대량 차단 스크립트가 잘못된 CIDR을 받아 정상 고객까지 끊을 수 있으므로 입력 형식과 최대 범위를 검증해야 합니다.', '실행 결과를 남기지 않으면 문제 재현과 책임 추적이 불가능합니다.'], ['dry-run·샘플 검증', '최소 권한 계정', 'idempotent 설계', '실행 전후 diff와 감사 로그', '중단·롤백 버튼'], [['Dry-run','실제 변경 없이 예상 결과 확인','샘플·diff'],['Idempotent','반복 실행해도 상태가 안정적','중복·재시도'],['Guardrail','위험한 실행을 제한하는 장치','범위·승인·중단']]),
  'automation-2': makeModule('로그 검색 쿼리', '로그 쿼리는 많은 데이터를 빠르게 읽기 위한 조사 언어입니다. 시간창, 필드, 집계, 중복 제거를 명확히 해야 결과를 믿을 수 있습니다.', '검색어보다 질문을 먼저 씁니다. “어떤 호스트가 어떤 시간에 어떤 사용자로 외부 주소와 통신했는가”처럼 필요한 필드를 정의한 뒤 쿼리를 만듭니다.', ['질문 정의', '시간창 설정', '필드 필터', '집계·상관', '결과 검증'], ['시간창이 너무 넓으면 정상 이벤트에 묻히고 너무 좁으면 최초 침해를 놓칠 수 있습니다.', '동일 이벤트 중복 수집은 탐지 건수와 KPI를 부풀릴 수 있습니다.'], ['쿼리 버전·작성자·목적 기록', '표본 원본 로그와 결과 대조', '쿼리 성능과 권한 제한', '오탐·누락 테스트 케이스 관리'], [['Time window','조사 시간 범위','침해 전후 여유'],['Aggregation','같은 사건을 묶는 집계','count·group by'],['Pivot','한 필드에서 다른 증거로 이동','host·user·IP']]),
  'automation-3': makeModule('정책 검증 스크립트', '정책 검증은 배포 전에 과도한 허용·중복·고아 객체·만료 예외를 자동으로 찾아내는 안전망입니다.', '정책을 파싱할 때 형식 검증과 의미 검증을 분리합니다. 문법이 맞아도 any-any, 만료일 없음, 승인 티켓 없음은 운영상 실패입니다.', ['정책 export', '스키마 검사', '위험 규칙 탐지', 'diff·리뷰', '승인·배포'], ['정책 문법은 정상이어도 광범위한 source와 destination이 보안 위험을 만들 수 있습니다.', '검증 스크립트 자체가 오래되면 새 필드를 놓칠 수 있어 샘플 fixture를 유지합니다.'], ['high-risk rule 차단', '예외·만료·owner 필수 검사', 'PR 또는 change ticket 리뷰', '실제 장비 결과와 회귀 테스트'], [['Schema validation','필드·형식 검사','누락·타입·범위'],['Shadow rule','앞 규칙에 가려진 규칙','도달 가능성'],['Regression','기존 정상 흐름이 유지되는지 확인','fixture·expected result']]),
  'automation-4': makeModule('운영 자동화 포트폴리오', '자동화 포트폴리오는 “무엇을 자동화했는가”보다 시간 절감, 오류 감소, 위험 통제가 증명되는 결과물입니다.', '자동화 대상별 빈도·절감시간·실패 영향·복구 난이도·데이터 민감도를 점수화해 투자 순서를 정합니다.', ['업무 목록화', '효과·위험 점수', '작은 프로토타입', '운영 전환', '성과 측정'], ['월 1회 보고서보다 매일 반복하는 로그 정제가 자동화 효과가 클 수 있지만 데이터 접근권한을 함께 설계해야 합니다.', '절감 시간만 보고 자동화하면 수동 검토가 사라져 품질이 낮아질 수 있습니다.'], ['자동화 전후 시간·오류율 비교', 'human-in-the-loop 유지', '권한·시크릿·로그 관리', '운영 중단과 인수인계 문서화'], [['ROI','투입 대비 효과','시간·오류·위험'],['Human-in-the-loop','중요 판단에 운영자 참여','승인·검토'],['Runbook','자동화 실패 시 수동 절차','복구·인계']]),
  'career-1': makeModule('경력기술서 구조', '경력기술서는 사용한 제품 목록이 아니라 문제·역할·판단·결과·재발 방지를 증명하는 문서입니다.', 'SAR 또는 STAR 구조로 한 사례를 쓰고, 담당 범위와 수치를 분리해 공백기 이후에도 실제 운영 경험이 보이게 합니다.', ['채용요건 분해', '사례 선택', '내 역할 분리', '성과 수치화', '증거 연결'], ['“EDR 운영”보다 “5천 단말 정책 배포와 오탐 예외를 월 20건에서 5건으로 감소”처럼 범위와 결과를 보여줘야 합니다.', '팀 성과를 개인 성과처럼 쓰지 않고 내가 판단·실행한 부분을 명확히 합니다.'], ['문제·조치·결과·교훈 1쪽 정리', '정책서·RCA·보고서 샘플 연결', '수치는 기준일과 산정 방법 표시', '기술 용어 뒤에 업무 영향을 설명'], [['SAR','상황·행동·결과','경험 구조'],['Scope','내가 책임진 범위','자산·고객·기간'],['Evidence','주장을 뒷받침하는 산출물','문서·지표']]),
  'career-2': makeModule('기술면접 대비', '기술면접은 용어를 많이 아는지보다 장애나 경보를 어떤 순서로 좁히는지 평가합니다.', '답변은 가설→확인 명령·로그→안전한 조치→복구 검증→고객 보고 순서로 말하면 실무성이 드러납니다.', ['질문 재정의', '가설 2~3개', '확인 순서', '조치·검증', '보고·재발방지'], ['VPN 접속 장애에 비밀번호 재설정만 반복하면 인증 이후 터널·라우팅·정책 문제를 놓칩니다.', 'EDR 격리는 빠르지만 업무 핵심 단말이면 영향과 예외 통신을 함께 판단해야 합니다.'], ['답변마다 사실과 가설 구분', '고위험 조치는 승인·증거보존 언급', '복구 후 같은 증상 재검증', '고객 공지와 RCA까지 마무리'], [['Hypothesis','검증할 원인 가설','가능성·영향'],['Trade-off','보안·가용성·비용의 균형','판단 근거'],['Verification','조치가 효과가 있었는지 확인','재현·지표']]),
  'career-3': makeModule('자격증 로드맵', '정보보안기사·ISMS-P·CISSP는 목적과 학습 방식이 다릅니다. 기사 이론은 기술 기반을, ISMS-P는 관리체계와 증적을, CISSP는 폭넓은 위험·거버넌스를 강화합니다.', '현재 지원 직무의 요구사항과 부족한 기초를 기준으로 순서를 정하고, 자격증 공부 결과를 운영 산출물로 바꿉니다.', ['직무요건 분석', '기초 진단', '과목별 계획', '문제풀이', '실무 산출물'], ['자격증 암기만 하면 면접에서 실제 정책 변경·장애 대응 질문에 연결하지 못할 수 있습니다.', '시험 기준과 일정은 변경될 수 있으므로 공식 기관의 최신 공지를 확인해야 합니다.'], ['주간 과목별 문제 수와 오답률 기록', '오답을 운영 사례로 다시 설명', '공식 출제기준 버전 기록', '자격증 내용과 직무 역량 매핑'], [['Exam blueprint','시험이 평가하는 범위','과목·항목·기준'],['Wrong note','틀린 이유를 재정리한 기록','개념·판단 오류'],['Transfer','시험 지식을 실무로 옮기기','정책·RCA·보고서']]),
  'career-4': makeModule('12주 포트폴리오', '12주 포트폴리오는 읽은 내용을 증거로 쌓는 프로젝트입니다. 매주 하나의 운영 문서를 완성해 최종 면접 자료로 묶습니다.', '네트워크 진단서·정책 변경서·EDR 탐지 분석·RCA·월간 보고서·자동화 검증 결과를 하나의 사건 흐름으로 연결합니다.', ['요구사항 매핑', '주차별 산출물', '리뷰·수정', '면접 스토리', '최종 포트폴리오'], ['문서가 예쁘기만 하고 입력 데이터·판단 근거·검증 결과가 없으면 실무 증거로 약합니다.', '가상의 실습은 가상임을 표시하고 실제 운영 경험과 섞어 쓰지 않습니다.'], ['문서마다 목적·범위·가정·증거·결론 포함', '동료 관점으로 이해 가능성 리뷰', '민감정보·실제 고객정보 제거', '각 산출물을 채용요건 한 항목과 연결'], [['Deliverable','학습 결과물','진단서·RCA·보고서'],['Assumption','실습에서 둔 가정','범위·제약'],['Traceability','요구사항과 결과 연결','채용요건·증거']]),
}

topicModules['network-1'].layers = deepLessons.network.layers;

const examQuestions = [
  { id:'net-q1', sector:'network', category:'네트워크 보안', q:'TCP/IP 4계층 모델에서 IP 주소를 사용해 서로 다른 네트워크 사이의 경로를 결정하는 계층은?', choices:['네트워크 액세스 계층','인터넷 계층','전송 계층','응용 계층'], answer:1, explain:'인터넷 계층은 IP 주소와 라우팅으로 네트워크 간 패킷 전달을 담당합니다. TCP/UDP의 포트와 신뢰성은 전송 계층의 역할입니다.' },
  { id:'net-q2', sector:'network', category:'네트워크 보안', q:'TCP SYN flood에 대한 대응으로 가장 거리가 먼 것은?', choices:['SYN cookie 적용','연결 요청 속도 제한','DDoS 방어 장비 연계','모든 외부 TCP 포트 영구 허용'], answer:3, explain:'SYN flood는 연결 대기 자원을 소진시키는 공격입니다. 무조건 허용은 공격면을 넓히므로 필요한 서비스만 제한적으로 노출해야 합니다.' },
  { id:'endpoint-q1', sector:'endpoint', category:'시스템 보안', q:'EDR 경보를 분석할 때 침해 여부 판단에 가장 유용한 조합은?', choices:['파일명만 확인','프로세스 트리·명령줄·사용자·네트워크 행위 확인','화면 해상도 확인','백신 제품명만 확인'], answer:1, explain:'EDR은 단일 파일명이 아니라 실행 계보와 행위를 함께 분석하는 것이 핵심입니다. 최초 실행 경로와 네트워크 연결을 함께 확인해야 합니다.' },
  { id:'endpoint-q2', sector:'endpoint', category:'시스템 보안', q:'업무 프로그램 오탐 예외를 운영할 때 가장 적절한 방법은?', choices:['전사 영구 예외','예외 사유·범위·만료일·승인자·대체통제 기록','탐지 기능 전체 비활성화','사용자 요청만으로 즉시 허용'], answer:1, explain:'예외는 위험 수용이므로 범위와 기간을 제한하고 만료·재검토가 가능해야 합니다.' },
  { id:'ns-q1', sector:'network-security', category:'네트워크 보안', q:'방화벽 정책 설계에서 최소권한 원칙에 가장 부합하는 것은?', choices:['any-any 허용 후 로그만 수집','출발지·목적지·서비스를 업무 범위로 제한하고 기본 거부 적용','모든 포트 허용','관리자 IP를 인터넷 전체에 공개'], answer:1, explain:'필요한 통신만 구체적으로 허용하고 나머지는 기본 거부하는 것이 최소권한과 방어 심층화에 맞습니다.' },
  { id:'ns-q2', sector:'network-security', category:'네트워크 보안', q:'VPN 인증은 성공했지만 내부 서버 접속이 되지 않는다. 우선 확인 순서로 적절한 것은?', choices:['사용자 PC 교체→비밀번호 변경','터널·주소 할당·라우팅·목적지 방화벽 정책 확인','WAF 룰 전체 삭제','모든 내부 서버 재부팅'], answer:1, explain:'인증 성공은 터널 이후의 통신까지 보장하지 않습니다. 터널 생성, 가상 주소, 라우팅, 목적지 정책을 단계별로 분리합니다.' },
  { id:'policy-q1', sector:'policy', category:'관리체계·운영', q:'정책 변경 승인 전에 반드시 정의해야 할 항목으로 가장 적절한 것은?', choices:['변경 목적·영향 범위·성공 기준·롤백 조건','담당자의 선호 색상','사내 전체 비밀번호','장비의 배경화면'], answer:0, explain:'변경은 목적과 영향, 검증 기준, 실패 시 복구 방법이 있어야 통제된 운영이 됩니다.' },
  { id:'policy-q2', sector:'policy', category:'관리체계·운영', q:'보안 정책 예외 관리에 대한 설명으로 옳은 것은?', choices:['예외는 영구 허용이 원칙이다','예외에는 만료일과 재검토일을 둘 수 있다','승인 기록은 필요 없다','대체 통제는 고려하지 않는다'], answer:1, explain:'예외는 제한된 기간의 위험 수용입니다. 소유자, 사유, 범위, 만료일, 대체 통제를 남겨야 합니다.' },
  { id:'incident-q1', sector:'incident', category:'시스템 보안', q:'서로 다른 장비 로그의 사건 순서를 분석할 때 가장 먼저 확인할 것은?', choices:['로그 화면의 글꼴','NTP와 타임존 등 시간 기준의 일치 여부','장비 제조사의 로고','사용자 모니터 크기'], answer:1, explain:'시간이 맞지 않으면 공격·장애 타임라인이 뒤섞입니다. 수집기·장비·서버의 시간 기준을 먼저 확인합니다.' },
  { id:'incident-q2', sector:'incident', category:'관리체계·운영', q:'RCA(근본 원인 분석)에 대한 설명으로 가장 적절한 것은?', choices:['담당자 한 명을 지목하고 종료한다','증상·직접 원인·기여 요인·재발 방지책을 구분한다','로그를 삭제하고 복구만 한다','고객에게 원인을 공유하지 않는다'], answer:1, explain:'RCA는 비난이 아니라 재발 방지 목적입니다. 타임라인과 증거를 바탕으로 원인 계층과 개선 액션을 구분합니다.' },
  { id:'customer-q1', sector:'customer', category:'관리체계·운영', q:'B2B 장애 접수 시 가장 먼저 정리해야 할 정보 조합은?', choices:['고객의 추측만 기록','발생 시각·영향 범위·재현 절차·최근 변경·증거','담당자 이름만 기록','장비 가격만 기록'], answer:1, explain:'고객 표현을 사실·영향·재현·최근 변경·증거로 바꾸면 기술 분석과 우선순위 판단이 가능해집니다.' },
  { id:'customer-q2', sector:'customer', category:'관리체계·운영', q:'정기 보안 운영 보고서의 좋은 지표로 가장 적절한 것은?', choices:['탐지 건수 하나만 표시','심각도별 처리시간·미해결 위험·재발 추세·개선 조치','보고서 페이지 수','회의 참석자 수만 표시'], answer:1, explain:'운영 보고는 숫자 나열보다 위험·추세·처리 품질·다음 조치를 보여줘야 합니다.' },
  { id:'automation-q1', sector:'automation', category:'시스템 보안', q:'대량 정책 변경 자동화 전에 가장 안전한 절차는?', choices:['검증 없이 전체 실행','dry-run·샘플 검증·승인·롤백 준비 후 실행','관리자 계정 공유','실행 로그 미수집'], answer:1, explain:'고위험 자동화는 실제 변경 전 결과를 예측하고, 승인과 롤백 경로를 확보해야 합니다.' },
  { id:'automation-q2', sector:'automation', category:'관리체계·운영', q:'자동화 계정 운영의 보안 원칙으로 옳은 것은?', choices:['모든 시스템 관리자 권한 부여','최소 권한·시크릿 분리·감사 로그·실행 범위 제한','비밀번호를 코드에 하드코딩','공유 계정으로 실행'], answer:1, explain:'자동화 계정은 권한과 비밀정보가 집중되므로 최소권한과 감사 가능성을 보장해야 합니다.' },
  { id:'career-q1', sector:'career', category:'정보보호 일반', q:'위험 처리 전략 중 위험을 줄이는 통제를 추가하고 잔여 위험을 모니터링하는 것은?', choices:['위험 회피','위험 완화','위험 무시','자산 폐기만'], answer:1, explain:'위험 완화는 통제 적용으로 발생 가능성 또는 영향을 낮추고 잔여 위험을 관리하는 전략입니다.' },
  { id:'career-q2', sector:'career', category:'정보보호 일반', q:'면접에서 “VPN 장애를 어떻게 분석했나요?”에 대한 가장 좋은 답변 구조는?', choices:['제품명만 나열','가설→확인 순서→조치→복구 검증→고객 보고','모르겠다고 답하고 종료','사용자에게 재시도만 요청'], answer:1, explain:'운영 직무는 판단 순서와 검증, 커뮤니케이션을 함께 평가합니다. 기술 조치와 서비스 영향 설명을 연결해야 합니다.' },
]

function studyDiagram(guide) { return `<div class="study-flow">${guide.flow.map((step, i) => `<div class="flow-node"><span>${String(i + 1).padStart(2, '0')}</span><b>${step}</b></div>${i < guide.flow.length - 1 ? '<i class="flow-arrow">→</i>' : ''}`).join('')}</div>` }

function openTopic(id) { if (!topics.some((t) => t.id === id)) return; state.selectedTopic = id; state.page = 'study'; syncRoute(); render(); window.scrollTo({ top: 0, behavior: 'smooth' }); }

function bind() {
  document.querySelectorAll('[data-page]').forEach((el) => el.addEventListener('click', () => { state.page = el.dataset.page; if (state.page !== 'study') state.selectedTopic = null; syncRoute(); render(); window.scrollTo({ top: 0, behavior: 'smooth' }) }))
  document.querySelectorAll('[data-topic]').forEach((el) => el.addEventListener('click', () => openTopic(el.dataset.topic)))
  document.querySelectorAll('[data-sector]').forEach((el) => el.addEventListener('click', () => { state.page = 'learn'; state.filter = el.dataset.sector; syncRoute(); render() }))
  document.querySelectorAll('[data-filter]').forEach((el) => el.addEventListener('click', () => { state.filter = el.dataset.filter; syncRoute(); render() }))
  document.querySelectorAll('[data-exam-filter]').forEach((el) => el.addEventListener('click', () => { state.examFilter = el.dataset.examFilter; state.examIndex = 0; syncRoute(); render() }))
  document.querySelectorAll('[data-answer]').forEach((el) => el.addEventListener('click', () => { const list = state.examFilter === '전체' ? examQuestions : examQuestions.filter((q) => q.sector === state.examFilter); const q = list[state.examIndex % list.length]; if (state.examAnswers[q.id]?.solved) return; const picked = Number(el.dataset.answer); state.examAnswers[q.id] = { picked, solved: true, correct: picked === q.answer }; localStorage.setItem('secops-exam', JSON.stringify(state.examAnswers)); render() }))
  const nextQuestion = document.querySelector('[data-next]'); if (nextQuestion) nextQuestion.onclick = () => { state.examIndex += 1; syncRoute(); render() }
  document.querySelectorAll('[data-complete]').forEach((el) => el.addEventListener('click', (e) => { e.stopPropagation(); state.completed[el.dataset.complete] = !state.completed[el.dataset.complete]; save(); render() }))
  document.querySelectorAll('[data-check]').forEach((el) => el.addEventListener('change', (e) => { state.completed[e.target.dataset.check] = e.target.checked; save() }))
  const saveNote = document.querySelector('#save-note'); if (saveNote) saveNote.onclick = () => { const id = state.selectedTopic; state.notes[id] = document.querySelector('#topic-note').value; save(); saveNote.textContent = '저장 완료 ✓' }
  const completeTopic = document.querySelector('#complete-topic'); if (completeTopic) completeTopic.onclick = () => { const id = state.selectedTopic; state.completed[id] = !state.completed[id]; save(); render() }
  const search = document.querySelector('#search'); if (search) { search.addEventListener('input', (e) => { state.search = e.target.value; const pos = e.target.selectionStart; render(); syncRoute(true); const next = document.querySelector('#search'); next.focus(); next.setSelectionRange(pos, pos) }) }
  const reset = document.querySelector('#reset-progress'); if (reset) reset.onclick = () => { if (confirm('모든 학습 진도와 체크리스트를 초기화할까요?')) { state.completed = {}; state.notes = {}; save(); render() } }
}

window.addEventListener('popstate', (event) => { restoreRoute(event.state || Object.fromEntries(new URLSearchParams(window.location.search))); render(); window.scrollTo({ top: 0, behavior: 'smooth' }) })

const initialRoute = Object.fromEntries(new URLSearchParams(window.location.search))
restoreRoute({ page: initialRoute.page, selectedTopic: initialRoute.topic, filter: initialRoute.filter, examFilter: initialRoute.filter, examIndex: initialRoute.q })
syncRoute(true)
render()
