const refs = [
  { name: 'NIST Cybersecurity Framework 2.0', org: 'NIST', url: 'https://www.nist.gov/cyberframework', tag: '프레임워크', desc: '보안 위험을 식별하고 우선순위를 정하는 공통 언어' },
  { name: 'KISA ISMS-P', org: 'KISA', url: 'https://isms.kisa.or.kr/', tag: '국내 기준', desc: '국내 정보보호·개인정보보호 관리체계 공식 자료' },
  { name: 'Microsoft Defender for Endpoint', org: 'Microsoft Learn', url: 'https://learn.microsoft.com/en-us/defender-endpoint/', tag: 'EDR', desc: '엔드포인트 온보딩, 탐지, 대응과 운영 가이드' },
  { name: 'OWASP Developer Guide', org: 'OWASP', url: 'https://owasp.org/www-project-developer-guide/', tag: '웹 보안', desc: '웹 애플리케이션 보안 원칙과 테스트 가이드' },
  { name: 'MITRE ATT&CK', org: 'MITRE', url: 'https://attack.mitre.org/', tag: '위협 분석', desc: '공격 전술·기술을 운영 탐지와 연결하는 지식베이스' },
  { name: 'IETF RFC Index', org: 'IETF', url: 'https://www.rfc-editor.org/', tag: '네트워크', desc: 'TCP/IP와 인터넷 프로토콜의 원문 표준' },
  { name: 'RFC 1122 Host Requirements', org: 'IETF', url: 'https://www.rfc-editor.org/rfc/rfc1122', tag: 'TCP/IP', desc: '인터넷 프로토콜 계층과 호스트 요구사항의 공식 표준' },
  { name: 'TCP/IP Learning Center', org: 'Cloudflare', url: 'https://www.cloudflare.com/learning/ddos/glossary/tcp-ip/', tag: '입문 설명', desc: '비전공자도 이해하기 쉬운 TCP/IP 개념 설명' },
  { name: 'Known Exploited Vulnerabilities', org: 'CISA', url: 'https://www.cisa.gov/known-exploited-vulnerabilities-catalog', tag: '취약점 사례', desc: '실제 공격에 악용된 취약점과 조치 우선순위' },
  { name: 'NIST SP 800-61 Rev. 3', org: 'NIST', url: 'https://csrc.nist.gov/pubs/sp/800/61/r3/final', tag: '사고 대응', desc: '사이버보안 사고 대응 권고사항과 고려사항' },
]

const sectorMeta = [
  { id: 'network', icon: '◎', color: 'cyan', title: '기초 네트워크', en: 'NETWORK FOUNDATION', desc: 'TCP/IP와 트래픽 흐름을 읽는 힘', outcome: '패킷 흐름과 장애 지점을 설명할 수 있다.' },
  { id: 'endpoint', icon: '◈', color: 'violet', title: '단말 보안', en: 'ENDPOINT SECURITY', desc: 'EDR·백신·DLP·NAC 운영', outcome: '단말 정책과 탐지 이벤트를 운영할 수 있다.' },
  { id: 'network-security', icon: '▣', color: 'amber', title: '네트워크 보안', en: 'NETWORK SECURITY', desc: 'Firewall·IPS·VPN·WAF 운영', outcome: '접근제어 정책과 보안 장비 장애를 분석할 수 있다.' },
  { id: 'policy', icon: '≡', color: 'green', title: '정책 운영', en: 'POLICY OPERATIONS', desc: '배포·예외·변경·롤백 프로세스', outcome: '변경 근거와 영향도를 기록하고 통제할 수 있다.' },
  { id: 'incident', icon: '△', color: 'red', title: '로그·장애 대응', en: 'INCIDENT RESPONSE', desc: '로그 분석과 원인 규명', outcome: '장애를 재현·분리·조치하고 재발을 방지할 수 있다.' },
  { id: 'customer', icon: '⊙', color: 'blue', title: 'B2B 고객 운영', en: 'CUSTOMER OPERATIONS', desc: 'SLA·기술 협의·정기 보고', outcome: '기술 내용을 고객 언어와 보고서로 전환할 수 있다.' },
  { id: 'automation', icon: '⌁', color: 'pink', title: '운영 자동화', en: 'AUTOMATION', desc: '반복 업무를 안전하게 줄이기', outcome: '검증 가능한 스크립트와 운영 자동화를 설계할 수 있다.' },
  { id: 'career', icon: '↗', color: 'white', title: '취업 대비', en: 'CAREER READINESS', desc: '경력기술서·면접·자격증', outcome: '운영 경험을 증거와 성과 중심으로 설명할 수 있다.' },
]

const topicSeeds = {
  network: [
    ['TCP/IP 4계층', 'TCP/IP model', '기초', '계층별 역할과 캡슐화를 이해하고 장애 범위를 좁힌다.', '클라이언트 요청이 애플리케이션에서 NIC까지 내려가는 과정을 4계층으로 설명한다.', 'OSI 7계층과 TCP/IP 4계층을 대응시키고, 각 계층의 대표 로그를 적어본다.'],
    ['DNS와 HTTP 흐름', 'DNS / HTTP', '기초', '이름 해석부터 TLS, HTTP 응답까지의 정상 흐름을 기준선으로 만든다.', 'DNS는 성공하지만 HTTPS만 실패하는 상황에서 확인 순서를 설계한다.', 'nslookup/dig, curl, 브라우저 개발자 도구에서 확인할 지점을 정리한다.'],
    ['라우팅과 방화벽 기초', 'Routing / Firewall', '기초', '경로, 포트, 상태 추적을 분리해 네트워크 장애를 분석한다.', '특정 대역에서만 서버 443 포트가 타임아웃되는 장애를 분석한다.', '출발지·목적지·포트·경로·정책 순으로 확인하는 5단계 템플릿을 작성한다.'],
    ['패킷·로그 읽기', 'Packet & Log Reading', '실무', '패킷과 장비 로그에서 사실과 추정을 구분한다.', 'SYN 재전송이 반복되는 캡처를 보고 네트워크·서버·정책 후보를 분리한다.', '타임스탬프, 5-tuple, 상태코드, 상관관계 ID를 추출한다.'],
  ],
  endpoint: [
    ['EDR 운영 모델', 'EDR Operations', '기초', '수집·탐지·분석·격리·복구의 운영 생명주기를 이해한다.', '의심스러운 PowerShell 실행 이벤트가 들어온 뒤 초기 대응을 수행한다.', '탐지 심각도, 호스트 중요도, 사용자 영향으로 우선순위를 정한다.'],
    ['백신 정책과 예외', 'AV Policy', '기초', '실시간 보호, 검사 주기, 예외의 위험을 정책으로 관리한다.', '업무 프로그램이 오탐되는 상황에서 무조건 예외를 주지 않고 검증한다.', '예외 대상·기간·승인자·대체 통제를 기록한다.'],
    ['DLP 데이터 흐름', 'DLP', '실무', '데이터 분류와 채널 통제를 연결해 유출 위험을 줄인다.', 'USB로 대량 파일이 복사된 경보의 사실관계를 확인한다.', '데이터 유형, 사용자, 채널, 행위, 업무 필요성을 기준으로 판단한다.'],
    ['NAC 접근제어', 'NAC', '실무', '단말 식별·상태평가·격리·복귀 흐름을 운영한다.', '보안 에이전트가 중지된 단말이 격리망으로 이동한 상황을 조치한다.', '인증 실패와 정책 불일치를 구분하고 복귀 조건을 기록한다.'],
  ],
  'network-security': [
    ['Firewall 정책 설계', 'Firewall Rule Design', '기초', '최소권한과 명확한 객체·서비스·방향으로 정책을 설계한다.', '신규 B2B 고객의 HTTPS 연동 요청을 정책으로 변환한다.', '정책 목적, 출발지, 목적지, 서비스, 기간, 로그 여부를 정의한다.'],
    ['IPS 탐지와 예외', 'IPS Detection', '실무', '탐지 시그니처와 실제 공격 가능성을 분리해 예외를 통제한다.', '정상 API 호출이 공격 시그니처로 탐지된 이벤트를 검증한다.', '시그니처·원본 페이로드·반복성·대체 방어를 확인한다.'],
    ['VPN 인증·터널', 'VPN', '실무', '인증, 암호화, 터널, 라우팅을 분리해 접속 장애를 분석한다.', '인증은 성공하지만 내부 시스템에 접속되지 않는 장애를 분석한다.', '사용자 인증→터널→주소 할당→라우팅→목적지 정책 순으로 확인한다.'],
    ['WAF 요청 분석', 'WAF', '실무', '웹 요청·응답과 WAF 정책의 관계를 분석한다.', '특정 파라미터가 차단되어 403이 발생하는 이슈를 재현·완화한다.', 'URI, 메서드, 파라미터, 룰 ID, 원본 서버 응답을 비교한다.'],
  ],
  policy: [
    ['정책 배포 절차', 'Policy Deployment', '기초', '요청-검토-승인-테스트-배포-검증의 흐름을 표준화한다.', '긴급 차단 정책을 배포하면서 서비스 영향과 롤백을 함께 준비한다.', '변경 티켓, 사전 검증, 승인, 배포 시각, 사후 검증을 남긴다.'],
    ['예외 승인 관리', 'Exception Management', '실무', '예외는 영구 허용이 아니라 만료와 보완 통제를 가진 위험 수용이다.', '업무상 필요한 예외 요청의 위험도를 평가한다.', '사유·범위·만료일·승인자·대체 통제·재검토일을 기록한다.'],
    ['변경·롤백', 'Change & Rollback', '실무', '변경 전후 상태와 실패 시 복구 경로를 관리한다.', '정책 변경 후 일부 고객의 연결이 끊겨 즉시 롤백한다.', '변경 단위, 백업, 성공 기준, 관찰 시간, 롤백 트리거를 정의한다.'],
    ['SOP와 증적', 'SOP & Evidence', '실무', '반복 가능한 운영절차와 감사 가능한 증적을 만든다.', '감사 요청에 정책 이력과 승인 기록을 빠르게 제출한다.', '문서 버전, 소유자, 승인일, 점검 주기, 관련 티켓을 연결한다.'],
  ],
  incident: [
    ['로그 수집과 기준선', 'Logging Baseline', '기초', '정상 상태와 시간 동기화를 기준으로 이상을 찾는다.', '장비별 시간이 달라 사건 순서가 뒤섞인 로그를 정렬한다.', 'NTP, 소스, 필드, 보존기간, 수집 누락을 점검한다.'],
    ['장애 트리아지', 'Incident Triage', '실무', '영향도와 긴급도로 사건을 분류하고 대응자를 정한다.', '다수 고객의 접속 장애가 발생한 상황에서 우선순위를 정한다.', '영향 범위·확산성·보안성·복구 난이도로 우선순위를 점수화한다.'],
    ['원인 분석 RCA', 'Root Cause Analysis', '실무', '증상·직접 원인·기여 요인·근본 원인을 분리한다.', '정책 배포 이후 탐지량이 급증한 사건의 RCA를 작성한다.', '타임라인, 증거, 가설, 검증 결과, 재발 방지책을 기록한다.'],
    ['사고 후 개선', 'Post-Incident Review', '실무', '복구가 끝난 뒤 탐지·절차·문서·자동화를 개선한다.', '반복 장애의 액션 아이템을 담당자와 기한까지 확정한다.', '무엇이 잘못됐는지보다 어떤 통제를 개선할지 측정 가능하게 쓴다.'],
  ],
  customer: [
    ['B2B 이슈 접수', 'B2B Intake', '기초', '고객 표현을 기술 사실과 업무 영향으로 번역한다.', '고객이 “보안 솔루션이 전부 멈췄다”고 문의한 상황을 정리한다.', '고객·시각·영향·재현·최근 변경·증거를 한 장으로 정리한다.'],
    ['SLA와 우선순위', 'SLA & Priority', '실무', '기술 심각도와 고객 서비스 중요도를 함께 판단한다.', '긴급 장애와 단일 사용자 문의가 동시에 들어온 상황을 배분한다.', '응답 목표, 복구 목표, 중간 공지 주기, 에스컬레이션 조건을 확인한다.'],
    ['기술 협의 진행', 'Technical Workshop', '실무', '가정·제약·결정사항을 명시해 협의를 실행계획으로 바꾼다.', '고객의 방화벽 변경 요청을 보안·운영 조건과 함께 검토한다.', '아젠다, 결정권자, 액션, 기한, 미결 이슈를 회의록에 남긴다.'],
    ['정기 운영 보고', 'Service Reporting', '실무', '운영량보다 위험·추세·조치 중심으로 보고한다.', '월간 보고서에서 탐지 증가를 장애가 아닌 개선 지표로 설명한다.', 'KPI, 주요 사건, 정책 변경, 미해결 위험, 다음 달 계획을 제시한다.'],
  ],
  automation: [
    ['운영 자동화 원칙', 'Automation Guardrails', '기초', '자동화 범위·승인·검증·중단 장치를 먼저 설계한다.', '대량 정책 변경 스크립트의 오작동 위험을 줄인다.', 'dry-run, 입력 검증, 권한 최소화, 감사 로그, 롤백을 포함한다.'],
    ['로그 검색 쿼리', 'Log Querying', '실무', '필터·집계·상관관계로 반복 분석 시간을 줄인다.', '특정 호스트의 로그인 실패와 EDR 탐지를 시간순으로 묶는다.', '시간창, 키 필드, 중복 제거, 결과 보존, 오탐 검증을 적용한다.'],
    ['정책 검증 스크립트', 'Policy Validation', '실무', '변경 전후 정책의 누락·중복·과도한 허용을 자동 점검한다.', 'any-any 규칙과 만료된 예외를 사전 탐지한다.', '정책 ID, 소유자, 만료일, 영향 서비스, 승인 티켓을 검사한다.'],
    ['운영 자동화 포트폴리오', 'Automation Portfolio', '실무', '효과와 위험을 비교해 자동화 우선순위를 정한다.', '수작업 보고서 생성을 자동화할지 판단한다.', '빈도·절감시간·오류위험·복구가능성·데이터 민감도를 평가한다.'],
  ],
  career: [
    ['경력기술서 구조', 'Experience Story', '취업', '상황-행동-결과로 운영 경험을 증거화한다.', 'EDR 운영 경험을 제품 나열이 아닌 성과로 바꿔 쓴다.', '대상·문제·내 역할·조치·수치·재발 방지까지 한 사례로 정리한다.'],
    ['기술면접 대비', 'Technical Interview', '취업', '정답보다 판단 순서와 운영 trade-off를 설명한다.', 'VPN 접속 장애 질문에 확인 순서와 고객 커뮤니케이션을 함께 답한다.', '가설→확인→조치→검증→보고의 구조로 답변을 연습한다.'],
    ['자격증 로드맵', 'Certification Path', '취업', '정보보안기사·ISMS-P·CISSP의 목적과 시기를 구분한다.', '현재 경력과 학습 시간에 맞는 우선순위를 정한다.', '응시요건, 출제범위, 실무 연결성, 준비 기간을 비교한다.'],
    ['12주 포트폴리오', '12-week Portfolio', '취업', '학습 기록을 운영 플레이북과 면접 포트폴리오로 묶는다.', '12주 후 실제로 보여줄 산출물을 계획한다.', '네트워크 진단서, 정책변경서, RCA, 월간보고서, 자동화 예제를 완성한다.'],
  ],
}

const topics = Object.entries(topicSeeds).flatMap(([sector, items]) => items.map((item, index) => ({
  id: `${sector}-${index + 1}`, sector, title: item[0], en: item[1], level: item[2], summary: item[3], scenario: item[4], practice: item[5],
  terms: item[1].split(' / '),
  checks: ['핵심 개념을 내 말로 설명하기', '운영 절차를 순서대로 적기', '실무 시나리오의 확인 항목 만들기', '면접 답변 또는 운영 산출물 남기기'],
  questions: [`${item[0]}을 운영할 때 가장 먼저 확인할 것은 무엇인가?`, '정상 기준선과 예외 상황을 어떻게 구분할 것인가?', '변경 또는 조치 이후 성공 여부를 어떻게 검증할 것인가?'],
  refs: sector === 'network' ? [refs[5], refs[0]] : sector === 'endpoint' ? [refs[2], refs[4]] : sector === 'career' ? [refs[0], refs[1]] : [refs[0], refs[1]],
})))

const state = {
  page: 'dashboard', search: '', filter: '전체', selectedTopic: null,
  completed: JSON.parse(localStorage.getItem('secops-completed') || '{}'),
  notes: JSON.parse(localStorage.getItem('secops-notes') || '{}'),
}

const save = () => { localStorage.setItem('secops-completed', JSON.stringify(state.completed)); localStorage.setItem('secops-notes', JSON.stringify(state.notes)) }
const esc = (value) => String(value).replace(/[&<>"']/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))
const sector = (id) => sectorMeta.find((item) => item.id === id)
const doneCount = () => Object.values(state.completed).filter(Boolean).length
const pct = (n, total = topics.length) => Math.round((n / total) * 100)

function icon(name) {
  const icons = { dashboard: '⌂', learn: '◫', study: '▤', roadmap: '↗', matrix: '⊞', refs: '◌' }
  return icons[name] || '•'
}

function appShell(content) {
  return `<div class="app-shell"><aside class="sidebar"><div class="brand"><div class="brand-mark">S</div><div><strong>SECOPS</strong><span>FIELD GUIDE / 01</span></div></div><div class="side-label">NAVIGATION</div><nav>${[['dashboard','대시보드','Overview'],['learn','학습센터','Learning center'],['study','공부하기','Study center'],['roadmap','12주 로드맵','Study plan'],['matrix','역량 매트릭스','Job mapping'],['refs','레퍼런스','Official sources']].map(([id,kr,en]) => `<button class="nav-item ${state.page === id ? 'active' : ''}" data-page="${id}"><span class="nav-icon">${icon(id)}</span><span><b>${kr}</b><small>${en}</small></span></button>`).join('')}</nav><div class="sidebar-bottom"><div class="mini-progress"><div class="side-label">YOUR PROGRESS</div><div class="progress-number">${pct(doneCount())}<small>%</small></div><div class="progress-track"><i style="width:${pct(doneCount())}%"></i></div><p>${doneCount()} / ${topics.length} topics completed</p></div><div class="status-pill"><i></i> LOCAL MODE <span>●</span></div></div></aside><main class="main"><header class="topbar"><div class="breadcrumb">SECOPS FIELD GUIDE <span>/</span> ${state.page.toUpperCase()}</div><button class="reset-btn" id="reset-progress">진도 초기화</button></header>${content}</main></div>`
}

function dashboard() {
  const next = topics.find((t) => !state.completed[t.id]) || topics[0]
  const weak = sectorMeta.map((s) => ({ ...s, count: topics.filter((t) => t.sector === s.id).filter((t) => state.completed[t.id]).length })).sort((a,b) => a.count / 4 - b.count / 4)[0]
  return appShell(`<section class="page fade-in"><div class="hero"><div><div class="eyebrow"><i></i> OPERATIONS READINESS PROGRAM / 2026</div><h1>보안 운영,<br><em>다시 현장으로.</em></h1><p>5년의 공백을 실무 역량으로 연결하는<br>정보보안 솔루션 운영 학습 플레이북입니다.</p><button class="primary-btn" data-topic="${next.id}">다음 학습 시작 <span>→</span></button></div><div class="hero-orbit"><div class="orbit-ring ring-1"></div><div class="orbit-ring ring-2"></div><div class="orbit-ring ring-3"></div><div class="orbit-core"><span>OPS</span><b>${String(pct(doneCount())).padStart(2,'0')}</b><small>% READY</small></div><div class="orbit-dot dot-a"></div><div class="orbit-dot dot-b"></div><div class="orbit-dot dot-c"></div></div></div><div class="section-heading"><div><span class="eyebrow">COMMAND CENTER</span><h2>현재 학습 상태</h2></div><span class="live-tag"><i></i> LOCAL STORAGE ACTIVE</span></div><div class="stats-grid"><div class="stat-card accent"><span class="stat-label">TOTAL PROGRESS</span><strong>${pct(doneCount())}<small>%</small></strong><div class="progress-track"><i style="width:${pct(doneCount())}%"></i></div><p>${doneCount()}개 학습 주제 완료</p></div><div class="stat-card"><span class="stat-label">CURRENT PHASE</span><strong class="phase">${doneCount() < 8 ? '01' : doneCount() < 20 ? '02' : '03'} <small>/ 03</small></strong><p>${doneCount() < 8 ? '기초 기반 세우기' : doneCount() < 20 ? '운영 시나리오 훈련' : '취업 실전 준비'}</p></div><div class="stat-card"><span class="stat-label">WEAK SIGNAL</span><strong class="signal">${weak.title}</strong><p>${4 - weak.count}개 주제 남음 · 우선 학습 권장</p></div><div class="stat-card"><span class="stat-label">NEXT MILESTONE</span><strong class="milestone">12주</strong><p>운영 포트폴리오 완성 목표</p></div></div><div class="dashboard-grid"><div class="panel sector-panel"><div class="panel-head"><div><span class="eyebrow">SECTOR SCAN</span><h3>역량별 진행 현황</h3></div><button class="text-btn" data-page="learn">전체 보기 →</button></div><div class="sector-list">${sectorMeta.map((s) => { const done = topics.filter((t) => t.sector === s.id && state.completed[t.id]).length; return `<button class="sector-row" data-sector="${s.id}"><span class="sector-icon ${s.color}">${s.icon}</span><span class="sector-info"><b>${s.title}</b><small>${s.en}</small></span><span class="sector-bar"><i style="width:${pct(done,4)}%"></i></span><strong>${String(pct(done,4)).padStart(2,'0')}<small>%</small></strong><span class="row-arrow">↗</span></button>` }).join('')}</div></div><div class="panel focus-panel"><span class="eyebrow">RECOMMENDED NEXT</span><h3>${esc(next.title)}</h3><span class="topic-sector ${sector(next.sector).color}">${sector(next.sector).title} / ${next.level}</span><p>${esc(next.summary)}</p><div class="focus-bottom"><span>예상 35분</span><button class="circle-btn" data-topic="${next.id}">→</button></div></div></div></section>`)
}

function learnPage() {
  const filtered = topics.filter((t) => { const q = state.search.toLowerCase(); return (!q || `${t.title} ${t.en} ${t.summary}`.toLowerCase().includes(q)) && (state.filter === '전체' || t.sector === state.filter || t.level === state.filter) })
  return appShell(`<section class="page fade-in"><div class="page-title"><div><span class="eyebrow">KNOWLEDGE BASE / 08 SECTORS</span><h1>학습 섹터</h1><p>기초 개념에서 운영 문서와 면접 답변까지, 한 주제를 끝까지 연결합니다.</p></div><div class="title-count"><strong>${filtered.length}</strong><span>VISIBLE TOPICS</span></div></div><div class="toolbar"><div class="search-box"><span>⌕</span><input id="search" value="${esc(state.search)}" placeholder="주제, 용어, 운영 키워드 검색" /></div><div class="filter-wrap"><button class="filter-btn ${state.filter === '전체' ? 'selected' : ''}" data-filter="전체">전체</button>${sectorMeta.map((s) => `<button class="filter-btn ${state.filter === s.id ? 'selected' : ''}" data-filter="${s.id}">${s.title}</button>`).join('')}<button class="filter-btn ${state.filter === '실무' ? 'selected' : ''}" data-filter="실무">실무</button><button class="filter-btn ${state.filter === '취업' ? 'selected' : ''}" data-filter="취업">취업</button></div></div><div class="topic-grid">${filtered.map(topicCard).join('')}</div></section>`)
}

function topicCard(t) { const s = sector(t.sector); const complete = state.completed[t.id]; return `<article class="topic-card ${complete ? 'complete' : ''}" data-topic="${t.id}"><div class="card-top"><span class="sector-icon ${s.color}">${s.icon}</span><span class="topic-level">${t.level}</span><button class="check-btn ${complete ? 'checked' : ''}" data-complete="${t.id}">${complete ? '✓' : '○'}</button></div><span class="card-kicker">${s.en}</span><h3>${esc(t.title)}</h3><p>${esc(t.summary)}</p><div class="card-foot"><span>${t.terms.join(' · ')}</span><b>열기 ↗</b></div></article>` }

function roadmap() { const weeks = [['01–02','기초 기반','네트워크·로그·보안 운영의 공통 언어를 회복합니다.',['TCP/IP 4계층','DNS와 HTTP 흐름','로그 수집과 기준선','정책 배포 절차']],['03–05','솔루션 운영','단말과 네트워크 보안 장비의 운영 흐름을 익힙니다.',['EDR 운영 모델','백신 정책과 예외','Firewall 정책 설계','VPN 인증·터널','WAF 요청 분석']],['06–08','장애·고객 대응','트리아지, RCA, SLA와 기술 협의를 훈련합니다.',['장애 트리아지','원인 분석 RCA','B2B 이슈 접수','SLA와 우선순위','정기 운영 보고']],['09–10','자동화·문서화','정책 검증과 반복 업무 자동화 산출물을 만듭니다.',['운영 자동화 원칙','로그 검색 쿼리','정책 검증 스크립트','SOP와 증적']],['11–12','취업 실전','경험을 경력기술서와 기술면접 답변으로 전환합니다.',['경력기술서 구조','기술면접 대비','자격증 로드맵','12주 포트폴리오']]]; return appShell(`<section class="page fade-in"><div class="page-title"><div><span class="eyebrow">FIELD TRAINING / 12 WEEKS</span><h1>12주 로드맵</h1><p>매주 하나의 운영 산출물을 남기며 공백기를 실무 언어로 바꿉니다.</p></div></div><div class="roadmap">${weeks.map((w,i) => `<div class="roadmap-row"><div class="week-marker"><span>PHASE ${String(i+1).padStart(2,'0')}</span><strong>${w[0]}</strong></div><div class="roadmap-content"><div><span class="eyebrow">${w[1]}</span><h2>${w[2]}</h2></div><div class="roadmap-topics">${w[3].map((name) => {const t=topics.find(x=>x.title===name); return t ? `<button data-topic="${t.id}" class="roadmap-topic ${state.completed[t.id]?'done':''}"><i>${state.completed[t.id]?'✓':'○'}</i>${name}<span>→</span></button>` : ''}).join('')}</div></div></div>`).join('')}</div></section>`) }

function matrix() { const rows = [['EDR·백신·DLP·NAC','endpoint','탐지·정책·예외·격리 운영'],['정책 배포·예외·변경관리','policy','승인·테스트·롤백·증적'],['Firewall·IPS·VPN·WAF','network-security','접근제어·탐지·터널·웹 요청'],['장애 분석·트러블슈팅','incident','로그·트리아지·RCA·재발방지'],['B2B 운영 지원·기술 협의','customer','SLA·회의록·에스컬레이션'],['정기 보고·문서화','customer','KPI·위험·조치·다음 계획'],['운영 자동화','automation','쿼리·검증·스크립트·가드레일']]; return appShell(`<section class="page fade-in"><div class="page-title"><div><span class="eyebrow">JOB DESCRIPTION / MAPPING</span><h1>역량 매트릭스</h1><p>채용공고의 요구사항을 실제 학습 주제와 운영 증거에 매핑했습니다.</p></div></div><div class="panel matrix-panel"><div class="matrix-header"><span>채용 요구사항</span><span>학습 섹터</span><span>준비할 증거</span><span>상태</span></div>${rows.map(([req,sec,evidence])=>{const s=sector(sec);const related=topics.filter(t=>t.sector===sec);const done=related.filter(t=>state.completed[t.id]).length; return `<div class="matrix-row"><strong>${req}</strong><span class="matrix-sector"><i class="sector-icon ${s.color}">${s.icon}</i>${s.title}</span><span>${evidence}</span><span class="matrix-status ${done===related.length?'ready':''}">${done===related.length?'READY':`${done}/${related.length}`}</span></div>`}).join('')}</div><div class="callout"><span>◎</span><div><b>면접에서 보여줄 운영 증거</b><p>정책 변경서, 장애 RCA, 월간 운영 보고서, 로그 분석 쿼리, 예외 승인 기록을 포트폴리오 형태로 축적하세요.</p></div></div></section>`) }

function studyDocument(t) {
  const s = sector(t.sector); const guide = studyGuides[t.sector]; const deep = deepLessons[t.sector]; const note = state.notes[t.id] || '';
  const layers = deep.layers ? `<div class="layer-table"><div class="layer-head"><span>계층</span><span>무엇을 하나?</span><span>대표 기술·장비</span><span>주요 취약점</span></div>${deep.layers.map((l) => `<div class="layer-row"><b class="layer-number">${l[0]}</b><div><strong>${l[1]}</strong><p>${l[2]}</p></div><div><b>${l[3]}</b><p>${l[4]}</p></div><div><span class="risk-text">${l[5]}</span></div></div>`).join('')}</div>` : '';
  return `<article class="study-document"><div class="study-document-head"><div><span class="eyebrow">${s.en} / ${t.level}</span><h2>${deep.title}</h2><p class="study-lead">${deep.intro}</p></div><div class="study-badge"><span>학습 주제</span><b>${t.title}</b><small>${t.en}</small></div></div><div class="study-callout"><span>핵심 판단</span><p>${deep.important}</p></div>${layers}<div class="study-doc-grid"><div><section class="doc-section"><span class="eyebrow">01 / 이론을 운영 언어로 바꾸기</span><h3>${t.title}에서 꼭 알아야 할 것</h3><p>${guide.core}</p><div class="study-flow">${guide.flow.map((step, i) => `<div class="flow-node"><span>${String(i + 1).padStart(2, '0')}</span><b>${step}</b></div>${i < guide.flow.length - 1 ? '<i class="flow-arrow">→</i>' : ''}`).join('')}</div><p class="diagram-caption">정상 흐름은 <b>${guide.flow.join(' → ')}</b>입니다. 장애나 보안 이벤트가 생기면 이 흐름에서 어느 단계가 달라졌는지부터 확인합니다.</p></section><section class="doc-section"><span class="eyebrow">02 / 운영 순서</span><h3>실무에서 이렇게 확인합니다</h3><ol class="study-steps">${guide.steps.map((step, i) => `<li><b>${i + 1}</b><span>${step}</span></li>`).join('')}</ol></section><section class="doc-section"><span class="eyebrow">03 / 취약점과 실제 상황</span><h3>어떻게 문제가 생기는가</h3><div class="case-list">${deep.cases.map((c, i) => `<div class="case-card"><b>CASE ${String(i + 1).padStart(2, '0')}</b><p>${c}</p></div>`).join('')}</div></section><section class="doc-section"><span class="eyebrow">04 / 대응과 예방</span><h3>운영자가 준비할 통제</h3><ul class="defense-list">${deep.defense.map((d) => `<li><i>✓</i>${d}</li>`).join('')}</ul></section></div><aside class="study-aside"><div class="aside-card"><span class="eyebrow">TERM NOTES</span>${guide.terms.map(([term, desc]) => `<div class="term-item"><b>${term}</b><p>${desc}</p></div>`).join('')}</div><div class="aside-card"><span class="eyebrow">CHECK YOURSELF</span>${t.questions.map((q) => `<p class="question">? ${q}</p>`).join('')}</div><div class="aside-card"><span class="eyebrow">MY NOTES</span><textarea id="topic-note" placeholder="배운 내용을 내 말로 정리하세요...">${esc(note)}</textarea><button class="save-note" id="save-note">메모 저장</button></div><div class="aside-card"><span class="eyebrow">OFFICIAL REFERENCES</span>${[...t.refs, refs[6], refs[7], refs[8], refs[9]].filter((r, i, arr) => r && arr.findIndex((x) => x.name === r.name) === i).map((r) => `<a class="inline-ref" href="${r.url}" target="_blank" rel="noreferrer">${r.name} ↗</a>`).join('')}</div></aside></div><section class="doc-section doc-checks"><span class="eyebrow">05 / 학습 완료 체크</span>${t.checks.map((c, i) => `<label class="modal-check"><input type="checkbox" ${state.completed[`${t.id}-check-${i}`] ? 'checked' : ''} data-check="${t.id}-check-${i}"><span>${c}</span></label>`).join('')}<button class="complete-topic ${state.completed[t.id] ? 'completed' : ''}" id="complete-topic">${state.completed[t.id] ? '✓ 학습 완료됨' : '이 학습을 완료 처리'} <span>→</span></button></section></article>`;
}

function studyPage() {
  const selected = topics.find((t) => t.id === state.selectedTopic) || topics[0];
  return appShell(`<section class="page fade-in study-page"><div class="page-title"><div><span class="eyebrow">STUDY CENTER / THEORY + PRACTICE</span><h1>공부하기</h1><p>팝업 요약이 아니라, 한 주제를 끝까지 읽고 정리하는 실무 교재입니다.</p></div><div class="title-count"><strong>${topics.filter((t) => state.completed[t.id]).length}</strong><span>TOPICS DONE</span></div></div><div class="study-workspace"><aside class="study-nav"><div class="study-nav-title"><span class="eyebrow">COURSE INDEX</span><b>학습 목차</b></div>${sectorMeta.map((s) => `<div class="study-nav-group"><span>${s.icon} ${s.title}</span>${topics.filter((t) => t.sector === s.id).map((t) => `<button class="study-nav-topic ${selected.id === t.id ? 'active' : ''} ${state.completed[t.id] ? 'done' : ''}" data-topic="${t.id}"><i>${state.completed[t.id] ? '✓' : '○'}</i>${t.title}</button>`).join('')}</div>`).join('')}</aside><div class="study-content">${studyDocument(selected)}</div></div></section>`);
}

function references() { return appShell(`<section class="page fade-in"><div class="page-title"><div><span class="eyebrow">PRIMARY SOURCES / VERIFIED LINKS</span><h1>레퍼런스</h1><p>공식 표준·보안기관·제품 문서와 이해하기 쉬운 기술 해설을 함께 연결했습니다.</p></div></div><div class="ref-grid">${refs.map((r,i)=>`<a class="ref-card" href="${r.url}" target="_blank" rel="noreferrer"><div class="ref-index">${String(i+1).padStart(2,'0')}</div><span class="ref-tag">${r.tag}</span><h3>${r.name}</h3><p>${r.desc}</p><div class="ref-foot"><span>${r.org}</span><b>문서 열기 ↗</b></div></a>`).join('')}</div></section>`) }

function render() { const content = state.page === 'dashboard' ? dashboard() : state.page === 'learn' ? learnPage() : state.page === 'study' ? studyPage() : state.page === 'roadmap' ? roadmap() : state.page === 'matrix' ? matrix() : references(); document.querySelector('#app').innerHTML = content; bind(); }

const studyGuides = {
  network: { core: '보안 운영자는 장비 이름보다 트래픽의 흐름을 먼저 봅니다. 출발지·목적지·포트·프로토콜·시간을 기준으로 정상 흐름을 만들면 장애와 공격을 빠르게 분리할 수 있습니다.', steps: ['요청을 5-tuple(출발지 IP·목적지 IP·출발지 포트·목적지 포트·프로토콜)로 적기', 'DNS·TCP·TLS·HTTP를 시간순으로 확인하기', '라우팅과 방화벽 정책에서 끊기는 지점 찾기', '서버 로그와 패킷의 시간·상관관계 맞추기', '조치 후 동일 요청으로 복구를 검증하기'], flow: ['사용자', 'DNS', 'TCP/TLS', '보안장비', '서버'], terms: [['5-tuple','한 연결을 구분하는 다섯 가지 네트워크 값'],['SYN','TCP 연결을 시작하는 첫 패킷'],['Baseline','정상 상태에서 관찰되는 기준선']], output: '네트워크 장애 진단서' },
  endpoint: { core: '단말 보안은 설치 여부보다 수집·탐지·판단·격리·복구가 이어지는 운영 생명주기가 핵심입니다. 예외는 편의를 위한 허용이 아니라 만료일이 있는 위험 수용입니다.', steps: ['단말·사용자·업무 중요도 확인하기', '탐지 이벤트의 프로세스·파일·네트워크 행위 확인하기', '오탐·침해·정책 위반을 분류하기', '필요 시 격리하고 증거를 보존하기', '복구 후 정책·예외·재발 방지 검토하기'], flow: ['단말 수집', '탐지 이벤트', '분석/분류', '격리·조치', '복구/개선'], terms: [['EDR','단말 행위를 수집하고 탐지·대응하는 플랫폼'],['IOC','침해를 의심하게 하는 파일·해시·주소 등의 지표'],['NAC','단말 상태에 따라 네트워크 접근을 제어하는 시스템']], output: '단말 탐지 대응 기록' },
  'network-security': { core: '네트워크 보안 장비의 정책은 업무 흐름을 허용하되 과도한 접근을 막는 통제입니다. 모든 변경은 목적·범위·기간·로그·롤백을 함께 가져야 합니다.', steps: ['업무 통신의 출발지·목적지·서비스 정의하기', '최소권한 객체와 정책 순서 설계하기', '로그와 탐지 시그니처를 활성화하기', '테스트 트래픽으로 허용·차단 결과 확인하기', '만료·롤백·사후 검증 일정 기록하기'], flow: ['업무 요청', '정책 설계', '보안장비 검사', '허용/차단', '로그·보고'], terms: [['ACL','주소·포트·방향으로 접근을 허용하거나 차단하는 규칙'],['IPS','공격 패턴을 탐지하고 차단하는 보안 장비'],['WAF','웹 요청을 애플리케이션 앞에서 검사하는 방화벽']], output: '보안 정책 변경서' },
  policy: { core: '정책 운영의 품질은 좋은 규칙보다 좋은 변경 과정에서 나옵니다. 요청을 티켓으로 남기고, 영향도를 검토하고, 승인된 변경만 배포하며, 결과를 증적으로 남깁니다.', steps: ['요청 목적과 업무 영향 수집하기', '중복·과도한 허용·만료 여부 검토하기', '승인자와 테스트 범위 확정하기', '작은 단위로 배포하고 관찰하기', '성공 기준 또는 롤백 조건으로 종료하기'], flow: ['요청/티켓', '검토', '승인', '배포', '검증/롤백'], terms: [['Change','운영 환경에 영향을 주는 통제된 변경'],['Exception','기준 정책에서 한시적으로 벗어나는 승인된 예외'],['Rollback','변경 이전의 검증된 상태로 되돌리는 절차']], output: '정책 변경·승인 기록' },
  incident: { core: '장애 대응은 추측이 아니라 증거의 시간순 정리입니다. 영향 범위를 먼저 줄이고, 서비스 복구와 원인 분석을 분리해 진행한 뒤 재발 방지까지 닫습니다.', steps: ['영향 고객·서비스·시작 시각을 확정하기', '긴급도와 보안성을 기준으로 우선순위 정하기', '최근 변경·로그·지표에서 가설 세우기', '안전한 완화 조치 후 복구 여부 확인하기', '타임라인과 RCA, 액션 아이템 작성하기'], flow: ['알림/문의', '트리아지', '증거 수집', '완화·복구', 'RCA/개선'], terms: [['Triage','영향도와 긴급도로 사건을 분류하는 초기 판단'],['RCA','직접 원인과 근본 원인을 구분하는 분석'],['MTTR','장애 발생부터 복구까지 걸린 평균 시간']], output: '장애 RCA 보고서' },
  customer: { core: 'B2B 운영은 기술 문제를 고객의 업무 영향과 의사결정 언어로 바꾸는 일입니다. 빠른 답변보다 정확한 현재 상태·다음 조치·다음 공유 시각이 신뢰를 만듭니다.', steps: ['고객 표현을 사실·영향·요청으로 나누기', 'SLA 기준과 서비스 중요도로 우선순위 정하기', '확인 중인 가설과 필요한 자료를 명확히 요청하기', '중간 진행 상황과 다음 공유 시각 약속하기', '결과·재발 방지·미결 이슈를 보고서로 남기기'], flow: ['고객 문의', '사실/영향 정리', '기술 분석', '중간 공유', '결과 보고'], terms: [['SLA','응답·복구·공지에 대한 서비스 약속'],['Escalation','담당 범위나 심각도를 넘어 상위 지원으로 올리는 절차'],['KPI','운영 품질과 추세를 측정하는 핵심 지표']], output: 'B2B 운영 보고서' },
  automation: { core: '자동화는 빠르게 실행하는 코드가 아니라 실수를 통제하는 운영 장치입니다. 입력 검증, dry-run, 최소 권한, 감사 로그, 중단과 롤백을 먼저 설계합니다.', steps: ['반복 빈도와 수작업 오류를 측정하기', '자동화할 입력·출력·권한을 제한하기', 'dry-run과 샘플 검증 만들기', '실행 결과·변경 전후·실패를 기록하기', '중단·롤백과 운영자 승인 지점 정하기'], flow: ['운영 요청', '입력 검증', 'Dry-run', '승인 실행', '결과/감사로그'], terms: [['Dry-run','실제 변경 없이 결과만 미리 확인하는 실행'],['Idempotent','같은 작업을 반복해도 결과가 망가지지 않는 성질'],['Audit log','누가 언제 무엇을 실행했는지 남기는 기록']], output: '운영 자동화 설계서' },
  career: { core: '취업 준비의 핵심은 제품명을 나열하는 것이 아니라 문제를 어떻게 판단하고 조치했는지 증명하는 것입니다. 운영 산출물을 면접 답변과 경력기술서의 근거로 사용합니다.', steps: ['채용요건을 경험·지식·산출물로 분해하기', '상황-행동-결과(SAR)로 사례를 고르기', '수치·범위·내 역할·제약조건을 채우기', '정책서·RCA·보고서 형태의 증거 만들기', '기술면접에서 확인 순서와 trade-off 설명하기'], flow: ['채용요건', '경험 분해', '산출물', '성과 수치', '면접 답변'], terms: [['SAR','상황·행동·결과로 경험을 설명하는 구조'],['Trade-off','보안·가용성·운영비용 사이의 판단 균형'],['Portfolio','실무 판단을 보여주는 문서와 결과물 묶음']], output: '경력기술서·운영 포트폴리오' },
}

const deepLessons = {
  network: {
    title: 'TCP/IP 4계층을 한 번에 이해하기',
    intro: 'TCP/IP는 인터넷 통신을 설명하는 실무 모델입니다. 공식 인터넷 아키텍처는 출처에 따라 4계층 또는 링크·인터넷·전송·응용으로 표현하며, OSI 7계층과 일대일로 완전히 같은 모델은 아닙니다.',
    layers: [
      ['1', '네트워크 액세스 (Network Access)', '같은 네트워크 안에서 프레임을 전달합니다.', 'Ethernet, Wi-Fi, ARP, MAC', '스위치·무선 AP·VLAN', 'ARP spoofing, VLAN hopping, 무선 도청, 스위치 포트 무단 접속'],
      ['2', '인터넷 (Internet)', '서로 다른 네트워크 사이에서 패킷의 주소와 경로를 결정합니다.', 'IPv4/IPv6, ICMP, IPsec, BGP', '라우터·L3 스위치', 'IP spoofing, ICMP 악용, 라우팅 조작, 단편화 우회'],
      ['3', '전송 (Transport)', '프로세스와 프로세스 사이의 통신을 포트로 구분합니다.', 'TCP, UDP, QUIC', '방화벽·IPS·로드밸런서', 'SYN flood, 포트 스캔, UDP 증폭, 세션 탈취'],
      ['4', '응용 (Application)', '사용자가 실제로 사용하는 서비스의 규칙과 데이터를 다룹니다.', 'DNS, HTTP/HTTPS, SSH, SMTP, DHCP', 'WAF·프록시·EDR·메일 보안', '인증 우회, 주입, 피싱, 취약한 암호화, 악성 파일 전달'],
    ],
    important: '운영에서 가장 중요한 것은 계층 번호를 외우는 것이 아니라 “어느 계층에서 사실이 끊겼는가”를 찾는 순서입니다. 예를 들어 DNS가 성공했는지, TCP 443 연결이 됐는지, TLS 협상이 끝났는지, HTTP가 200을 반환했는지를 나누어 확인합니다.',
    cases: ['SYN flood: 짧은 시간에 TCP 연결 시작 요청을 대량 전송해 서버의 연결 대기 자원을 소진시키는 유형입니다. 방어는 SYN cookie, 연결 제한, DDoS 보호, 원본 서버 노출 최소화를 조합합니다.', 'ARP spoofing: 같은 L2 네트워크에서 게이트웨이의 MAC 정보를 속여 트래픽을 가로채는 유형입니다. 동적 ARP 검사, DHCP snooping, 네트워크 분리, 암호화 통신으로 위험을 줄입니다.', 'DNS spoofing/cache poisoning: 잘못된 IP를 응답해 사용자를 공격자 서버로 유도합니다. DNSSEC, 재귀 DNS 보안, HTTPS 인증서 검증, DNS 로그 모니터링이 대응책입니다.'],
    defense: ['자산과 정상 통신 기준선 만들기', '방화벽은 필요한 포트만 허용하고 관리 인터페이스를 분리하기', 'TLS·SSH·VPN으로 기밀성과 인증 보장하기', 'IDS/IPS·EDR·DNS·프록시 로그를 시간 기준으로 연결하기', 'CISA KEV와 제조사 보안 공지를 기준으로 패치 우선순위 정하기'],
  },
  endpoint: { title: '단말 보안 솔루션 운영 이론', intro: '단말 보안은 백신 하나를 설치하는 일이 아니라 단말의 상태를 수집하고, 이상 행위를 판단하고, 피해 확산을 막고, 정상 상태로 복구하는 운영 체계입니다.', important: 'EDR은 파일 이름만 보는 도구가 아니라 프로세스 트리·명령줄·사용자·네트워크 연결·지속성(persistence)을 함께 분석합니다. DLP는 데이터 분류와 업무 맥락이 없으면 오탐이 늘고, NAC는 인증과 단말 상태 평가가 핵심입니다.', cases: ['랜섬웨어: 정상 프로세스가 대량 파일 변경을 수행하면 행위 기반 탐지와 호스트 격리로 확산을 차단합니다.', '오탐 예외: 업무 프로그램을 영구 예외 처리하면 탐지 공백이 생깁니다. 해시·경로·서명·기간을 제한하고 만료일과 승인자를 남겨야 합니다.', '감염 단말: 네트워크 격리 전 휘발성 증거와 사용자 영향 범위를 확인하고, 복구 후 재발 방지 정책까지 검토합니다.'], defense: ['에이전트 설치·통신·정책 적용 상태 점검', '탐지 이벤트에서 프로세스 트리와 최초 실행 경로 확인', '격리 전후 증거 보존과 사용자 통지', '예외는 범위·기간·승인자·대체통제를 필수 기록', '복구 후 동일 IOC 재탐지와 정책 회귀 테스트'] },
  'network-security': { title: 'Firewall·IPS·VPN·WAF 이론', intro: '네트워크 보안 장비는 각각 다른 위치에서 다른 판단을 합니다. Firewall은 흐름을 허용·차단하고, IPS는 공격 패턴을 검사하고, VPN은 통신 구간을 보호하고, WAF는 웹 요청의 의미를 검사합니다.', important: '정책을 장비 이름으로 외우기보다 “어떤 트래픽을 어느 지점에서 어떤 근거로 차단하는가”로 이해해야 합니다. 특히 정책 순서, 기본 거부, 로그 활성화, 만료일이 운영 품질을 좌우합니다.', cases: ['any-any 허용: 빠른 장애 조치로 추가된 규칙이 장기간 남아 내부 확산 경로가 될 수 있습니다. 임시 규칙은 만료와 검토 티켓을 갖게 합니다.', 'IPS 오탐: 정상 API가 공격 시그니처에 걸릴 때 원본 요청·룰 ID·반복성을 확인한 뒤 좁은 예외를 적용합니다.', 'VPN 장애: 인증 성공과 내부 서비스 접근 성공은 다릅니다. 인증→터널→주소→라우팅→목적지 정책 순으로 분리합니다.'], defense: ['최소권한·기본거부·정책 순서 검토', '관리 인터페이스 별도 망과 MFA', '정책 변경 전후 로그와 롤백 파일 보존', 'WAF 차단은 룰 ID·요청·원본 응답을 함께 분석', '장비 자체의 취약점은 CISA KEV와 제조사 공지로 우선 조치'] },
  policy: { title: '정책·변경·예외 관리 이론', intro: '정책은 기술 설정이면서 조직의 위험 수용 결정입니다. 좋은 운영은 요청을 기록하고, 영향을 평가하고, 승인하고, 검증하고, 만료시키는 흐름을 반복합니다.', important: '예외는 “허용”이 아니라 정해진 기간 동안의 위험 수용입니다. 정책 이름만 바꾸는 것보다 목적·대상·기간·승인·로그·대체 통제를 남기는 것이 중요합니다.', cases: ['긴급 차단 후 서비스 장애: 긴급 변경도 사유와 승인자, 사후 검토 기한을 남기고 롤백 조건을 정해야 합니다.', '중복 정책: 위쪽의 광범위한 허용 규칙이 아래의 차단 규칙을 무력화할 수 있습니다. 정책 순서와 shadow rule을 점검합니다.', '만료된 예외: 정기 리포트에서 만료 예정·장기 예외·소유자 없는 예외를 분리해 정리합니다.'], defense: ['변경 티켓에 5W1H와 영향 범위 작성', '사전 백업·테스트·성공 기준·롤백 트리거 정의', '승인자와 실행자 분리', '배포 후 로그와 사용자 영향 검증', '예외 만료 리포트와 정기 접근 검토'] },
  incident: { title: '로그 분석과 장애 대응 이론', intro: '사고 대응은 알람에 반응하는 일이 아니라 증거를 보존하고, 영향 범위를 줄이고, 서비스를 복구하고, 원인을 설명하는 과정입니다.', important: 'NIST 사고 대응 흐름을 실무적으로 적용하면 준비→탐지·분석→대응→복구→사후 개선으로 이어집니다. 장애와 보안사고를 처음부터 완벽히 구분하려 하지 말고, 사실과 가설을 분리해 기록해야 합니다.', cases: ['로그 시간 불일치: NTP가 맞지 않으면 공격 타임라인이 뒤섞입니다. 수집기·장비·서버의 시간 오차를 먼저 확인합니다.', '알람 폭증: 동일 원인의 중복 이벤트를 묶고 영향도·확산성·자산 중요도로 우선순위를 조정합니다.', 'RCA 실패: “담당자 실수”로 끝내지 말고 직접 원인·기여 요인·탐지 실패·프로세스 개선을 나눠 작성합니다.'], defense: ['영향 범위·시작 시각·최근 변경 확인', '원본 로그와 증거 보존', '완화 조치와 원인 분석을 병렬로 진행', '복구 후 같은 증상 재현·검증', 'RCA에 담당자·기한·측정 가능한 개선 항목 포함'] },
  customer: { title: 'B2B 고객 보안 운영 이론', intro: 'B2B 솔루션 운영자는 기술자이면서 서비스 운영자입니다. 고객이 이해할 수 있는 영향과 다음 조치를 설명하고, 약속한 시각에 상태를 업데이트해야 합니다.', important: '고객 문의를 “증상·영향·원하는 조치”로 재작성하면 조사 방향이 선명해집니다. 기술적으로 맞는 말도 고객 업무 영향과 연결되지 않으면 좋은 운영 보고가 아닙니다.', cases: ['전체 장애처럼 보이는 단일 사용자 문제: 사용자·단말·망·정책 범위를 분리해 실제 영향도를 좁힙니다.', 'SLA 임박 장애: 기술 분석과 별개로 현재 상태·완화책·다음 공지 시각을 먼저 공유합니다.', '월간 탐지 증가: 단순 건수 대신 자산 중요도·심각도·처리 시간·재발 여부로 추세를 설명합니다.'], defense: ['접수 시각·영향·범위·재현 절차 기록', 'SLA 응답·복구·공지 기준 확인', '가설과 확인 중인 항목을 고객에게 구분해서 전달', '회의록에 결정·담당·기한·미결 이슈 기록', '정기 보고에 위험·추세·개선 결과 포함'] },
  automation: { title: '보안 운영 자동화 이론', intro: '보안 자동화는 권한이 큰 시스템을 빠르게 바꾸므로 일반 업무 자동화보다 안전장치가 더 중요합니다. 자동화 전후의 상태를 비교할 수 있어야 합니다.', important: '가장 먼저 자동화할 대상은 반복 빈도가 높고 규칙이 명확하며 실패 시 복구 가능한 작업입니다. 고위험 차단·삭제·대량 정책 변경은 승인과 dry-run을 남겨야 합니다.', cases: ['대량 정책 오타: 입력 검증과 샘플 실행 없이 전체 배포하면 서비스 장애가 발생합니다.', '자동화 계정 탈취: 최소 권한·시크릿 관리·실행 IP 제한·감사 로그로 피해 범위를 줄입니다.', '보고 자동화 오탐: 집계 기준과 중복 제거 규칙을 문서화하지 않으면 잘못된 KPI가 만들어집니다.'], defense: ['dry-run과 입력 스키마 검증', '최소 권한 서비스 계정과 시크릿 분리', '실행 전 승인·실행 후 결과 검증', '실패 시 중단·롤백·수동 전환', '코드 변경 리뷰와 테스트 로그 보존'] },
  career: { title: '정보보안기사·취업 이론 연결법', intro: '자격증 이론은 암기장으로 끝내지 말고 운영 상황에 연결해야 합니다. 네트워크·시스템·애플리케이션·관리체계의 개념을 실제 정책·로그·장애 사례로 설명하는 연습이 필요합니다.', important: '면접에서는 “무엇인가”보다 “어디서 확인하고, 왜 그렇게 판단하며, 어떻게 재발을 막는가”가 중요합니다. 모든 학습 주제를 하나의 운영 산출물로 바꾸면 경력 공백을 학습 결과로 설명할 수 있습니다.', cases: ['TCP/IP 질문: 4계층을 말한 뒤 DNS→TCP→TLS→HTTP 확인 순서를 장애 사례로 연결합니다.', '취약점 질문: CVE 번호 암기보다 영향 자산·악용 가능성·패치·완화·검증을 설명합니다.', '고객 대응 질문: 기술 조치와 함께 현재 상태·예상 시각·다음 공지 약속을 말합니다.'], defense: ['정보보안기사 과목을 8개 운영 섹터에 매핑', '한 주제마다 1쪽 요약과 1개 실습 산출물 작성', 'SAR 또는 STAR 구조로 경험 답변 정리', '공식 문서와 최신 취약점 공지 확인 습관화', '모르는 내용은 확인 경로와 검증 방법까지 답변'] },
}

function studyDiagram(guide) { return `<div class="study-flow">${guide.flow.map((step, i) => `<div class="flow-node"><span>${String(i + 1).padStart(2, '0')}</span><b>${step}</b></div>${i < guide.flow.length - 1 ? '<i class="flow-arrow">→</i>' : ''}`).join('')}</div>` }

function openTopic(id) { if (!topics.some((t) => t.id === id)) return; state.selectedTopic = id; state.page = 'study'; render(); window.scrollTo({ top: 0, behavior: 'smooth' }); }

function bind() { document.querySelectorAll('[data-page]').forEach((el)=>el.addEventListener('click',()=>{state.page=el.dataset.page;render()})); document.querySelectorAll('[data-topic]').forEach((el)=>el.addEventListener('click',()=>openTopic(el.dataset.topic))); document.querySelectorAll('[data-sector]').forEach((el)=>el.addEventListener('click',()=>{state.page='learn';state.filter=el.dataset.sector;render()})); document.querySelectorAll('[data-filter]').forEach((el)=>el.addEventListener('click',()=>{state.filter=el.dataset.filter;render()})); document.querySelectorAll('[data-complete]').forEach((el)=>el.addEventListener('click',(e)=>{e.stopPropagation();state.completed[el.dataset.complete]=!state.completed[el.dataset.complete];save();render()})); document.querySelectorAll('[data-check]').forEach((el)=>el.addEventListener('change',(e)=>{state.completed[e.target.dataset.check]=e.target.checked;save()})); const saveNote=document.querySelector('#save-note'); if(saveNote) saveNote.onclick=()=>{const id=state.selectedTopic;state.notes[id]=document.querySelector('#topic-note').value;save();saveNote.textContent='저장 완료 ✓'}; const completeTopic=document.querySelector('#complete-topic'); if(completeTopic) completeTopic.onclick=()=>{const id=state.selectedTopic;state.completed[id]=!state.completed[id];save();render()}; const search=document.querySelector('#search'); if(search){search.addEventListener('input',(e)=>{state.search=e.target.value;const pos=e.target.selectionStart;render();const next=document.querySelector('#search');next.focus();next.setSelectionRange(pos,pos)})} const reset=document.querySelector('#reset-progress'); if(reset) reset.onclick=()=>{if(confirm('모든 학습 진도와 체크리스트를 초기화할까요?')){state.completed={};state.notes={};save();render()}} }

render()
